package ast

const (
	FunctionDefinitionNodeType  = "function_definition"
	ExternalDeclarationNodeType = "external_declaration"
	VariableNodeType            = "variable"
	SentenceNodeType            = "sentence"
	EntryModifierNodeType       = "entry_modifier"
	ExternalModifierNodeType    = "external_modifier"
	SentenceEqNodeType          = "sentence_eq"
	SentenceBlockNodeType       = "sentence_block"
	SentenceBlockEndNodeType    = "sentence_block_end"
	SentenceLhsNodeType         = "sentence_lhs"
	SentenceRhsNodeType         = "sentence_rhs"
	ConditionNodeType           = "condition"
	BodyNodeType                = "body"
	SymbolsSeqNodeType          = "symbols"
	StringNodeType              = "string"
	NumberNodeType              = "number"
	IdentNodeType               = "ident"
	CommentNodeType             = "comment"
	FunctionCallNodeType        = "function_call"
	VariableTypeNodeType        = "type"
	FuncNameListNodeType        = "function_name_list"
	LineCommentNodeType         = "line_comment"
)
