#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 97
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 29

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_COMMA = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_EQ = 5,
  anon_sym_COLON = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LT = 9,
  anon_sym_GT = 10,
  anon_sym_DOT = 11,
  sym_ident = 12,
  anon_sym_s = 13,
  anon_sym_e = 14,
  anon_sym_t = 15,
  sym_string = 16,
  sym_number = 17,
  sym_symbols = 18,
  sym_entry_modifier = 19,
  anon_sym_DOLLAREXTERNAL = 20,
  anon_sym_DOLLAREXTERN = 21,
  anon_sym_DOLLAREXTRN = 22,
  anon_sym_SLASH_STAR = 23,
  aux_sym_comment_token1 = 24,
  anon_sym_STAR = 25,
  aux_sym_comment_token2 = 26,
  anon_sym_STAR_SLASH = 27,
  aux_sym_line_comment_token1 = 28,
  sym_source_file = 29,
  sym_external_declaration = 30,
  sym_function_name_list = 31,
  sym_function_definition = 32,
  sym_body = 33,
  sym_sentence = 34,
  sym_sentence_eq = 35,
  sym_sentence_block = 36,
  sym_sentence_lhs = 37,
  sym_sentence_rhs = 38,
  sym_sentence_block_end = 39,
  aux_sym__pattern = 40,
  sym_grouped_pattern = 41,
  sym_condition = 42,
  aux_sym__expr = 43,
  sym_function_call = 44,
  sym_grouped_expr = 45,
  sym_variable = 46,
  sym_type = 47,
  sym_external_modifier = 48,
  sym_comment = 49,
  sym_line_comment = 50,
  aux_sym_source_file_repeat1 = 51,
  aux_sym_function_name_list_repeat1 = 52,
  aux_sym_body_repeat1 = 53,
  aux_sym_sentence_eq_repeat1 = 54,
  aux_sym_comment_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [sym_ident] = "ident",
  [anon_sym_s] = "s",
  [anon_sym_e] = "e",
  [anon_sym_t] = "t",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_symbols] = "symbols",
  [sym_entry_modifier] = "entry_modifier",
  [anon_sym_DOLLAREXTERNAL] = "$EXTERNAL",
  [anon_sym_DOLLAREXTERN] = "$EXTERN",
  [anon_sym_DOLLAREXTRN] = "$EXTRN",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_STAR] = "*",
  [aux_sym_comment_token2] = "comment_token2",
  [anon_sym_STAR_SLASH] = "*/",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [sym_source_file] = "source_file",
  [sym_external_declaration] = "external_declaration",
  [sym_function_name_list] = "function_name_list",
  [sym_function_definition] = "function_definition",
  [sym_body] = "body",
  [sym_sentence] = "sentence",
  [sym_sentence_eq] = "sentence_eq",
  [sym_sentence_block] = "sentence_block",
  [sym_sentence_lhs] = "sentence_lhs",
  [sym_sentence_rhs] = "sentence_rhs",
  [sym_sentence_block_end] = "sentence_block_end",
  [aux_sym__pattern] = "_pattern",
  [sym_grouped_pattern] = "grouped_pattern",
  [sym_condition] = "condition",
  [aux_sym__expr] = "_expr",
  [sym_function_call] = "function_call",
  [sym_grouped_expr] = "grouped_expr",
  [sym_variable] = "variable",
  [sym_type] = "type",
  [sym_external_modifier] = "external_modifier",
  [sym_comment] = "comment",
  [sym_line_comment] = "line_comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_name_list_repeat1] = "function_name_list_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_sentence_eq_repeat1] = "sentence_eq_repeat1",
  [aux_sym_comment_repeat1] = "comment_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_ident] = sym_ident,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_t] = anon_sym_t,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_symbols] = sym_symbols,
  [sym_entry_modifier] = sym_entry_modifier,
  [anon_sym_DOLLAREXTERNAL] = anon_sym_DOLLAREXTERNAL,
  [anon_sym_DOLLAREXTERN] = anon_sym_DOLLAREXTERN,
  [anon_sym_DOLLAREXTRN] = anon_sym_DOLLAREXTRN,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_comment_token2] = aux_sym_comment_token2,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym_external_declaration] = sym_external_declaration,
  [sym_function_name_list] = sym_function_name_list,
  [sym_function_definition] = sym_function_definition,
  [sym_body] = sym_body,
  [sym_sentence] = sym_sentence,
  [sym_sentence_eq] = sym_sentence_eq,
  [sym_sentence_block] = sym_sentence_block,
  [sym_sentence_lhs] = sym_sentence_lhs,
  [sym_sentence_rhs] = sym_sentence_rhs,
  [sym_sentence_block_end] = sym_sentence_block_end,
  [aux_sym__pattern] = aux_sym__pattern,
  [sym_grouped_pattern] = sym_grouped_pattern,
  [sym_condition] = sym_condition,
  [aux_sym__expr] = aux_sym__expr,
  [sym_function_call] = sym_function_call,
  [sym_grouped_expr] = sym_grouped_expr,
  [sym_variable] = sym_variable,
  [sym_type] = sym_type,
  [sym_external_modifier] = sym_external_modifier,
  [sym_comment] = sym_comment,
  [sym_line_comment] = sym_line_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_name_list_repeat1] = aux_sym_function_name_list_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_sentence_eq_repeat1] = aux_sym_sentence_eq_repeat1,
  [aux_sym_comment_repeat1] = aux_sym_comment_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_symbols] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_modifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAREXTERNAL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAREXTERN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAREXTRN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_external_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_block] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_lhs] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_rhs] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_block_end] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pattern] = {
    .visible = false,
    .named = false,
  },
  [sym_grouped_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__expr] = {
    .visible = false,
    .named = false,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_external_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_name_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_eq_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block = 1,
  field_body = 2,
  field_condition = 3,
  field_entry = 4,
  field_expr = 5,
  field_func_name_list = 6,
  field_lhs = 7,
  field_name = 8,
  field_param = 9,
  field_pattern = 10,
  field_result = 11,
  field_rhs = 12,
  field_sentence_block = 13,
  field_sentence_eq = 14,
  field_type = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block] = "block",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_entry] = "entry",
  [field_expr] = "expr",
  [field_func_name_list] = "func_name_list",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_param] = "param",
  [field_pattern] = "pattern",
  [field_result] = "result",
  [field_rhs] = "rhs",
  [field_sentence_block] = "sentence_block",
  [field_sentence_eq] = "sentence_eq",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 3},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 1},
  [12] = {.index = 15, .length = 1},
  [13] = {.index = 16, .length = 2},
  [14] = {.index = 18, .length = 1},
  [15] = {.index = 19, .length = 1},
  [16] = {.index = 20, .length = 1},
  [17] = {.index = 21, .length = 2},
  [18] = {.index = 23, .length = 2},
  [19] = {.index = 25, .length = 2},
  [20] = {.index = 27, .length = 2},
  [21] = {.index = 29, .length = 2},
  [22] = {.index = 31, .length = 2},
  [23] = {.index = 33, .length = 1},
  [24] = {.index = 34, .length = 2},
  [25] = {.index = 36, .length = 2},
  [26] = {.index = 38, .length = 3},
  [27] = {.index = 41, .length = 3},
  [28] = {.index = 44, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
    {field_name, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_sentence_eq, 0},
  [4] =
    {field_sentence_block, 0},
  [5] =
    {field_condition, 0},
  [6] =
    {field_body, 2},
    {field_entry, 0},
    {field_name, 1},
  [9] =
    {field_name, 0},
    {field_name, 1},
  [11] =
    {field_func_name_list, 1},
  [12] =
    {field_block, 1},
  [13] =
    {field_rhs, 1},
  [14] =
    {field_lhs, 0},
  [15] =
    {field_condition, 0, .inherited = true},
  [16] =
    {field_condition, 0, .inherited = true},
    {field_condition, 1, .inherited = true},
  [18] =
    {field_body, 1},
  [19] =
    {field_pattern, 2},
  [20] =
    {field_result, 1},
  [21] =
    {field_block, 2},
    {field_lhs, 0},
  [23] =
    {field_lhs, 0},
    {field_rhs, 2},
  [25] =
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
  [27] =
    {field_name, 2},
    {field_type, 0},
  [29] =
    {field_block, 2},
    {field_condition, 0, .inherited = true},
  [31] =
    {field_condition, 0, .inherited = true},
    {field_rhs, 2},
  [33] =
    {field_name, 1},
  [34] =
    {field_body, 2},
    {field_expr, 0},
  [36] =
    {field_pattern, 3},
    {field_result, 1},
  [38] =
    {field_block, 3},
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
  [41] =
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
    {field_rhs, 3},
  [44] =
    {field_name, 1},
    {field_param, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '"', 2,
        '$', 10,
        '\'', 3,
        '(', 29,
        ')', 30,
        '*', 55,
        ',', 24,
        '.', 33,
        '/', 8,
        ':', 28,
        ';', 23,
        '<', 31,
        '=', 27,
        '>', 32,
        'e', 37,
        's', 36,
        't', 38,
        '{', 25,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 2,
        '\'', 3,
        '(', 29,
        ')', 30,
        '*', 54,
        ',', 24,
        '/', 8,
        ':', 28,
        ';', 23,
        '<', 31,
        '=', 27,
        '>', 32,
        'e', 37,
        's', 36,
        't', 38,
        '{', 25,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(42);
      if (lookahead == '-') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(55);
      if (lookahead == '/') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead == 0x401 ||
          (0x410 <= lookahead && lookahead <= 0x44f) ||
          lookahead == 0x451) ADVANCE(53);
      if (lookahead != 0) ADVANCE(50);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(48);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '/') ADVANCE(8);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(17);
      if (lookahead == 'R') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'L') ADVANCE(45);
      END_STATE();
    case 13:
      if (lookahead == 'N') ADVANCE(18);
      if (lookahead == 'X') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'N') ADVANCE(47);
      END_STATE();
    case 15:
      if (lookahead == 'N') ADVANCE(46);
      END_STATE();
    case 16:
      if (lookahead == 'R') ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == 'R') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 'T') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'T') ADVANCE(11);
      END_STATE();
    case 20:
      if (lookahead == 'Y') ADVANCE(44);
      END_STATE();
    case 21:
      if (eof) ADVANCE(22);
      ADVANCE_MAP(
        '$', 10,
        '*', 54,
        ',', 24,
        '.', 33,
        '/', 8,
        ';', 23,
        '=', 27,
        '{', 25,
        '}', 26,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_s);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_e);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_t);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_symbols);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_symbols);
      if (lookahead == '\'') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_symbols);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_entry_modifier);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTERNAL);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTERN);
      if (lookahead == 'A') ADVANCE(12);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTRN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(48);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '/') ADVANCE(51);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead == 0x401 ||
          (0x410 <= lookahead && lookahead <= 0x44f) ||
          lookahead == 0x451) ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '*') ADVANCE(50);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_' ||
          lookahead == 0x401 ||
          (0x410 <= lookahead && lookahead <= 0x44f) ||
          lookahead == 0x451) ADVANCE(50);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead == '/') ADVANCE(59);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_STAR);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_comment_token2);
      if (lookahead == '*') ADVANCE(54);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(56);
      if (lookahead == '/') ADVANCE(61);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(62);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '*') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 21},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 21},
  [43] = {.lex_state = 21},
  [44] = {.lex_state = 21},
  [45] = {.lex_state = 21},
  [46] = {.lex_state = 21},
  [47] = {.lex_state = 21},
  [48] = {.lex_state = 21},
  [49] = {.lex_state = 21},
  [50] = {.lex_state = 21},
  [51] = {.lex_state = 21},
  [52] = {.lex_state = 21},
  [53] = {.lex_state = 21},
  [54] = {.lex_state = 21},
  [55] = {.lex_state = 7},
  [56] = {.lex_state = 21},
  [57] = {.lex_state = 21},
  [58] = {.lex_state = 7},
  [59] = {.lex_state = 21},
  [60] = {.lex_state = 7},
  [61] = {.lex_state = 21},
  [62] = {.lex_state = 21},
  [63] = {.lex_state = 21},
  [64] = {.lex_state = 21},
  [65] = {.lex_state = 21},
  [66] = {.lex_state = 21},
  [67] = {.lex_state = 7},
  [68] = {.lex_state = 21},
  [69] = {.lex_state = 7},
  [70] = {.lex_state = 21},
  [71] = {.lex_state = 21},
  [72] = {.lex_state = 21},
  [73] = {.lex_state = 21},
  [74] = {.lex_state = 21},
  [75] = {.lex_state = 21},
  [76] = {.lex_state = 21},
  [77] = {.lex_state = 21},
  [78] = {.lex_state = 21},
  [79] = {.lex_state = 21},
  [80] = {.lex_state = 21},
  [81] = {.lex_state = 21},
  [82] = {.lex_state = 21},
  [83] = {.lex_state = 21},
  [84] = {.lex_state = 60},
  [85] = {.lex_state = 21},
  [86] = {.lex_state = 21},
  [87] = {.lex_state = 21},
  [88] = {.lex_state = 9},
  [89] = {.lex_state = 21},
  [90] = {.lex_state = 21},
  [91] = {.lex_state = 21},
  [92] = {.lex_state = 21},
  [93] = {.lex_state = 21},
  [94] = {(TSStateId)(-1)},
  [95] = {(TSStateId)(-1)},
  [96] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [sym_line_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_symbols] = ACTIONS(1),
    [sym_entry_modifier] = ACTIONS(1),
    [anon_sym_DOLLAREXTERNAL] = ACTIONS(1),
    [anon_sym_DOLLAREXTERN] = ACTIONS(1),
    [anon_sym_DOLLAREXTRN] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_STAR] = ACTIONS(5),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(90),
    [sym_external_declaration] = STATE(50),
    [sym_function_definition] = STATE(50),
    [sym_external_modifier] = STATE(66),
    [sym_comment] = STATE(1),
    [sym_line_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(43),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_ident] = ACTIONS(9),
    [sym_entry_modifier] = ACTIONS(11),
    [anon_sym_DOLLAREXTERNAL] = ACTIONS(13),
    [anon_sym_DOLLAREXTERN] = ACTIONS(15),
    [anon_sym_DOLLAREXTRN] = ACTIONS(13),
    [anon_sym_SLASH_STAR] = ACTIONS(3),
    [anon_sym_STAR] = ACTIONS(17),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      anon_sym_COMMA,
    ACTIONS(21), 1,
      anon_sym_RBRACE,
    ACTIONS(23), 1,
      anon_sym_EQ,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    STATE(4), 1,
      aux_sym_body_repeat1,
    STATE(29), 1,
      aux_sym__pattern,
    STATE(51), 1,
      sym_sentence_lhs,
    STATE(53), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(72), 1,
      sym_condition,
    STATE(76), 1,
      sym_sentence,
    STATE(78), 1,
      sym_sentence_eq,
    STATE(79), 1,
      sym_sentence_block,
    STATE(82), 1,
      sym_type,
    STATE(2), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [67] = 19,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(33), 1,
      anon_sym_COMMA,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    ACTIONS(38), 1,
      anon_sym_EQ,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(50), 1,
      sym_string,
    STATE(29), 1,
      aux_sym__pattern,
    STATE(51), 1,
      sym_sentence_lhs,
    STATE(53), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(72), 1,
      sym_condition,
    STATE(78), 1,
      sym_sentence_eq,
    STATE(79), 1,
      sym_sentence_block,
    STATE(82), 1,
      sym_type,
    STATE(93), 1,
      sym_sentence,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(44), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(47), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(3), 3,
      sym_comment,
      sym_line_comment,
      aux_sym_body_repeat1,
  [132] = 20,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(19), 1,
      anon_sym_COMMA,
    ACTIONS(23), 1,
      anon_sym_EQ,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      aux_sym_body_repeat1,
    STATE(29), 1,
      aux_sym__pattern,
    STATE(51), 1,
      sym_sentence_lhs,
    STATE(53), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(62), 1,
      sym_sentence,
    STATE(72), 1,
      sym_condition,
    STATE(78), 1,
      sym_sentence_eq,
    STATE(79), 1,
      sym_sentence_block,
    STATE(82), 1,
      sym_type,
    STATE(4), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [199] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(57), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LT,
    ACTIONS(69), 1,
      sym_string,
    STATE(82), 1,
      sym_type,
    ACTIONS(63), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(66), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 3,
      aux_sym__expr,
      sym_comment,
      sym_line_comment,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
    ACTIONS(55), 5,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_GT,
  [245] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    STATE(15), 1,
      aux_sym__expr,
    STATE(71), 1,
      sym_sentence_rhs,
    STATE(82), 1,
      sym_type,
    ACTIONS(72), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(6), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [293] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    STATE(15), 1,
      aux_sym__expr,
    STATE(75), 1,
      sym_sentence_rhs,
    STATE(82), 1,
      sym_type,
    ACTIONS(82), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(7), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [341] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    STATE(15), 1,
      aux_sym__expr,
    STATE(73), 1,
      sym_sentence_rhs,
    STATE(82), 1,
      sym_type,
    ACTIONS(84), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(8), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [389] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    STATE(15), 1,
      aux_sym__expr,
    STATE(80), 1,
      sym_sentence_rhs,
    STATE(82), 1,
      sym_type,
    ACTIONS(86), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(9), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [437] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    STATE(10), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(90), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(88), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [468] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(92), 1,
      anon_sym_COLON,
    STATE(22), 1,
      aux_sym__expr,
    STATE(81), 1,
      sym_sentence_block_end,
    STATE(82), 1,
      sym_type,
    STATE(11), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [515] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    ACTIONS(96), 1,
      anon_sym_LBRACE,
    STATE(26), 1,
      aux_sym__pattern,
    STATE(65), 1,
      sym_body,
    STATE(82), 1,
      sym_type,
    ACTIONS(94), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    STATE(12), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [562] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(92), 1,
      anon_sym_COLON,
    STATE(22), 1,
      aux_sym__expr,
    STATE(74), 1,
      sym_sentence_block_end,
    STATE(82), 1,
      sym_type,
    STATE(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [609] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(92), 1,
      anon_sym_COLON,
    STATE(22), 1,
      aux_sym__expr,
    STATE(61), 1,
      sym_sentence_block_end,
    STATE(82), 1,
      sym_type,
    STATE(14), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [656] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    STATE(5), 1,
      aux_sym__expr,
    STATE(82), 1,
      sym_type,
    ACTIONS(98), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(15), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [701] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(92), 1,
      anon_sym_COLON,
    STATE(22), 1,
      aux_sym__expr,
    STATE(70), 1,
      sym_sentence_block_end,
    STATE(82), 1,
      sym_type,
    STATE(16), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [748] = 13,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    ACTIONS(96), 1,
      anon_sym_LBRACE,
    STATE(33), 1,
      aux_sym__pattern,
    STATE(77), 1,
      sym_body,
    STATE(82), 1,
      sym_type,
    ACTIONS(100), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    STATE(17), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [795] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(104), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      sym_string,
    STATE(82), 1,
      sym_type,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(102), 3,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_RPAREN,
    ACTIONS(107), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(110), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(18), 3,
      aux_sym__pattern,
      sym_comment,
      sym_line_comment,
  [835] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(116), 1,
      anon_sym_RPAREN,
    STATE(21), 1,
      aux_sym__expr,
    STATE(82), 1,
      sym_type,
    STATE(19), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [879] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(118), 1,
      anon_sym_GT,
    STATE(25), 1,
      aux_sym__expr,
    STATE(82), 1,
      sym_type,
    STATE(20), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [923] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(120), 1,
      anon_sym_RPAREN,
    STATE(5), 1,
      aux_sym__expr,
    STATE(82), 1,
      sym_type,
    STATE(21), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [967] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(122), 1,
      anon_sym_COLON,
    STATE(5), 1,
      aux_sym__expr,
    STATE(82), 1,
      sym_type,
    STATE(22), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [1011] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(124), 1,
      anon_sym_COLON,
    STATE(5), 1,
      aux_sym__expr,
    STATE(82), 1,
      sym_type,
    STATE(23), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [1055] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(126), 1,
      anon_sym_COLON,
    STATE(23), 1,
      aux_sym__expr,
    STATE(82), 1,
      sym_type,
    STATE(24), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [1099] = 12,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(74), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      anon_sym_LT,
    ACTIONS(80), 1,
      sym_string,
    ACTIONS(128), 1,
      anon_sym_GT,
    STATE(5), 1,
      aux_sym__expr,
    STATE(82), 1,
      sym_type,
    STATE(25), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(78), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(27), 3,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [1143] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    STATE(18), 1,
      aux_sym__pattern,
    STATE(82), 1,
      sym_type,
    ACTIONS(130), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    STATE(26), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1184] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    STATE(27), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(134), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(132), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [1213] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    STATE(28), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(138), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(136), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [1242] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    STATE(18), 1,
      aux_sym__pattern,
    STATE(82), 1,
      sym_type,
    ACTIONS(140), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    STATE(29), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1283] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    STATE(30), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(144), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(142), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [1312] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    STATE(31), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(148), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(146), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [1341] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    STATE(32), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(152), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(150), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [1370] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    STATE(18), 1,
      aux_sym__pattern,
    STATE(82), 1,
      sym_type,
    ACTIONS(154), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    STATE(33), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1411] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    STATE(26), 1,
      aux_sym__pattern,
    STATE(82), 1,
      sym_type,
    ACTIONS(94), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    STATE(34), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1452] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    STATE(33), 1,
      aux_sym__pattern,
    STATE(82), 1,
      sym_type,
    ACTIONS(100), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    STATE(35), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1493] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    ACTIONS(156), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym__pattern,
    STATE(82), 1,
      sym_type,
    STATE(36), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1533] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(31), 1,
      sym_string,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      aux_sym__pattern,
    STATE(82), 1,
      sym_type,
    STATE(37), 2,
      sym_comment,
      sym_line_comment,
    STATE(41), 2,
      sym_grouped_pattern,
      sym_variable,
    ACTIONS(27), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1573] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    STATE(38), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(160), 5,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(162), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
  [1599] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    STATE(39), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(164), 5,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(166), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
  [1625] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    STATE(40), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(36), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      sym_string,
    ACTIONS(168), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
  [1651] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    STATE(41), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(170), 5,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(172), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
  [1677] = 10,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(174), 1,
      ts_builtin_sym_end,
    ACTIONS(176), 1,
      sym_ident,
    ACTIONS(179), 1,
      sym_entry_modifier,
    ACTIONS(185), 1,
      anon_sym_DOLLAREXTERN,
    STATE(66), 1,
      sym_external_modifier,
    ACTIONS(182), 2,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
    STATE(50), 2,
      sym_external_declaration,
      sym_function_definition,
    STATE(42), 3,
      sym_comment,
      sym_line_comment,
      aux_sym_source_file_repeat1,
  [1712] = 11,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_ident,
    ACTIONS(11), 1,
      sym_entry_modifier,
    ACTIONS(15), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    STATE(42), 1,
      aux_sym_source_file_repeat1,
    STATE(66), 1,
      sym_external_modifier,
    ACTIONS(13), 2,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
    STATE(43), 2,
      sym_comment,
      sym_line_comment,
    STATE(50), 2,
      sym_external_declaration,
      sym_function_definition,
  [1749] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(192), 1,
      anon_sym_DOLLAREXTERN,
    STATE(44), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(190), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1772] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(196), 1,
      anon_sym_DOLLAREXTERN,
    STATE(45), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(194), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1795] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(200), 1,
      anon_sym_DOLLAREXTERN,
    STATE(46), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(198), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1818] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(204), 1,
      anon_sym_DOLLAREXTERN,
    STATE(47), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(202), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1839] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(208), 1,
      anon_sym_DOLLAREXTERN,
    STATE(48), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(206), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1860] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(212), 1,
      anon_sym_DOLLAREXTERN,
    STATE(49), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(210), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1881] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(216), 1,
      anon_sym_DOLLAREXTERN,
    STATE(50), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(214), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1902] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(218), 1,
      anon_sym_COMMA,
    ACTIONS(220), 1,
      anon_sym_EQ,
    STATE(54), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(72), 1,
      sym_condition,
    STATE(51), 2,
      sym_comment,
      sym_line_comment,
  [1925] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    ACTIONS(225), 1,
      anon_sym_EQ,
    STATE(72), 1,
      sym_condition,
    STATE(52), 3,
      sym_comment,
      sym_line_comment,
      aux_sym_sentence_eq_repeat1,
  [1946] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(227), 1,
      anon_sym_COMMA,
    ACTIONS(229), 1,
      anon_sym_EQ,
    STATE(52), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(72), 1,
      sym_condition,
    STATE(53), 2,
      sym_comment,
      sym_line_comment,
  [1969] = 7,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(231), 1,
      anon_sym_COMMA,
    ACTIONS(233), 1,
      anon_sym_EQ,
    STATE(52), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(72), 1,
      sym_condition,
    STATE(54), 2,
      sym_comment,
      sym_line_comment,
  [1992] = 5,
    ACTIONS(235), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(237), 1,
      aux_sym_comment_token1,
    ACTIONS(240), 1,
      anon_sym_STAR,
    ACTIONS(243), 1,
      anon_sym_STAR_SLASH,
    STATE(55), 3,
      sym_comment,
      sym_line_comment,
      aux_sym_comment_repeat1,
  [2010] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(245), 1,
      anon_sym_SEMI,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    STATE(56), 3,
      sym_comment,
      sym_line_comment,
      aux_sym_function_name_list_repeat1,
  [2028] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(250), 1,
      anon_sym_SEMI,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    STATE(59), 1,
      aux_sym_function_name_list_repeat1,
    STATE(57), 2,
      sym_comment,
      sym_line_comment,
  [2048] = 6,
    ACTIONS(235), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_comment_token1,
    ACTIONS(256), 1,
      anon_sym_STAR,
    ACTIONS(258), 1,
      anon_sym_STAR_SLASH,
    STATE(55), 1,
      aux_sym_comment_repeat1,
    STATE(58), 2,
      sym_comment,
      sym_line_comment,
  [2068] = 6,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(252), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_SEMI,
    STATE(56), 1,
      aux_sym_function_name_list_repeat1,
    STATE(59), 2,
      sym_comment,
      sym_line_comment,
  [2088] = 6,
    ACTIONS(235), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(254), 1,
      aux_sym_comment_token1,
    ACTIONS(256), 1,
      anon_sym_STAR,
    ACTIONS(262), 1,
      anon_sym_STAR_SLASH,
    STATE(58), 1,
      aux_sym_comment_repeat1,
    STATE(60), 2,
      sym_comment,
      sym_line_comment,
  [2108] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(264), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(61), 2,
      sym_comment,
      sym_line_comment,
  [2123] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(266), 1,
      anon_sym_SEMI,
    ACTIONS(268), 1,
      anon_sym_RBRACE,
    STATE(62), 2,
      sym_comment,
      sym_line_comment,
  [2140] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_LBRACE,
    STATE(49), 1,
      sym_body,
    STATE(63), 2,
      sym_comment,
      sym_line_comment,
  [2157] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(245), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    STATE(64), 2,
      sym_comment,
      sym_line_comment,
  [2172] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(270), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(65), 2,
      sym_comment,
      sym_line_comment,
  [2187] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(272), 1,
      sym_ident,
    STATE(83), 1,
      sym_function_name_list,
    STATE(66), 2,
      sym_comment,
      sym_line_comment,
  [2204] = 3,
    ACTIONS(235), 1,
      anon_sym_SLASH_STAR,
    STATE(67), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(243), 3,
      aux_sym_comment_token1,
      anon_sym_STAR,
      anon_sym_STAR_SLASH,
  [2217] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(96), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_body,
    STATE(68), 2,
      sym_comment,
      sym_line_comment,
  [2234] = 3,
    ACTIONS(235), 1,
      anon_sym_SLASH_STAR,
    STATE(69), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(274), 3,
      aux_sym_comment_token1,
      anon_sym_STAR,
      anon_sym_STAR_SLASH,
  [2247] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(276), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(70), 2,
      sym_comment,
      sym_line_comment,
  [2262] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(278), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(71), 2,
      sym_comment,
      sym_line_comment,
  [2277] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(280), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    STATE(72), 2,
      sym_comment,
      sym_line_comment,
  [2292] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(282), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(73), 2,
      sym_comment,
      sym_line_comment,
  [2307] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(284), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(74), 2,
      sym_comment,
      sym_line_comment,
  [2322] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(286), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(75), 2,
      sym_comment,
      sym_line_comment,
  [2337] = 5,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(53), 1,
      anon_sym_RBRACE,
    ACTIONS(266), 1,
      anon_sym_SEMI,
    STATE(76), 2,
      sym_comment,
      sym_line_comment,
  [2354] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(288), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(77), 2,
      sym_comment,
      sym_line_comment,
  [2369] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(290), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(78), 2,
      sym_comment,
      sym_line_comment,
  [2384] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(292), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(79), 2,
      sym_comment,
      sym_line_comment,
  [2399] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(294), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(80), 2,
      sym_comment,
      sym_line_comment,
  [2414] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(296), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(81), 2,
      sym_comment,
      sym_line_comment,
  [2429] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(298), 1,
      anon_sym_DOT,
    STATE(82), 2,
      sym_comment,
      sym_line_comment,
  [2443] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(300), 1,
      anon_sym_SEMI,
    STATE(83), 2,
      sym_comment,
      sym_line_comment,
  [2457] = 4,
    ACTIONS(5), 1,
      anon_sym_STAR,
    ACTIONS(235), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(302), 1,
      aux_sym_line_comment_token1,
    STATE(84), 2,
      sym_comment,
      sym_line_comment,
  [2471] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(304), 1,
      sym_ident,
    STATE(85), 2,
      sym_comment,
      sym_line_comment,
  [2485] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(306), 1,
      sym_ident,
    STATE(86), 2,
      sym_comment,
      sym_line_comment,
  [2499] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(308), 1,
      anon_sym_DOT,
    STATE(87), 2,
      sym_comment,
      sym_line_comment,
  [2513] = 4,
    ACTIONS(5), 1,
      anon_sym_STAR,
    ACTIONS(235), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(310), 1,
      aux_sym_comment_token2,
    STATE(88), 2,
      sym_comment,
      sym_line_comment,
  [2527] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(312), 1,
      sym_ident,
    STATE(89), 2,
      sym_comment,
      sym_line_comment,
  [2541] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(314), 1,
      ts_builtin_sym_end,
    STATE(90), 2,
      sym_comment,
      sym_line_comment,
  [2555] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(316), 1,
      sym_ident,
    STATE(91), 2,
      sym_comment,
      sym_line_comment,
  [2569] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(318), 1,
      sym_ident,
    STATE(92), 2,
      sym_comment,
      sym_line_comment,
  [2583] = 4,
    ACTIONS(3), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(17), 1,
      anon_sym_STAR,
    ACTIONS(266), 1,
      anon_sym_SEMI,
    STATE(93), 2,
      sym_comment,
      sym_line_comment,
  [2597] = 1,
    ACTIONS(320), 1,
      ts_builtin_sym_end,
  [2601] = 1,
    ACTIONS(322), 1,
      ts_builtin_sym_end,
  [2605] = 1,
    ACTIONS(324), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 67,
  [SMALL_STATE(4)] = 132,
  [SMALL_STATE(5)] = 199,
  [SMALL_STATE(6)] = 245,
  [SMALL_STATE(7)] = 293,
  [SMALL_STATE(8)] = 341,
  [SMALL_STATE(9)] = 389,
  [SMALL_STATE(10)] = 437,
  [SMALL_STATE(11)] = 468,
  [SMALL_STATE(12)] = 515,
  [SMALL_STATE(13)] = 562,
  [SMALL_STATE(14)] = 609,
  [SMALL_STATE(15)] = 656,
  [SMALL_STATE(16)] = 701,
  [SMALL_STATE(17)] = 748,
  [SMALL_STATE(18)] = 795,
  [SMALL_STATE(19)] = 835,
  [SMALL_STATE(20)] = 879,
  [SMALL_STATE(21)] = 923,
  [SMALL_STATE(22)] = 967,
  [SMALL_STATE(23)] = 1011,
  [SMALL_STATE(24)] = 1055,
  [SMALL_STATE(25)] = 1099,
  [SMALL_STATE(26)] = 1143,
  [SMALL_STATE(27)] = 1184,
  [SMALL_STATE(28)] = 1213,
  [SMALL_STATE(29)] = 1242,
  [SMALL_STATE(30)] = 1283,
  [SMALL_STATE(31)] = 1312,
  [SMALL_STATE(32)] = 1341,
  [SMALL_STATE(33)] = 1370,
  [SMALL_STATE(34)] = 1411,
  [SMALL_STATE(35)] = 1452,
  [SMALL_STATE(36)] = 1493,
  [SMALL_STATE(37)] = 1533,
  [SMALL_STATE(38)] = 1573,
  [SMALL_STATE(39)] = 1599,
  [SMALL_STATE(40)] = 1625,
  [SMALL_STATE(41)] = 1651,
  [SMALL_STATE(42)] = 1677,
  [SMALL_STATE(43)] = 1712,
  [SMALL_STATE(44)] = 1749,
  [SMALL_STATE(45)] = 1772,
  [SMALL_STATE(46)] = 1795,
  [SMALL_STATE(47)] = 1818,
  [SMALL_STATE(48)] = 1839,
  [SMALL_STATE(49)] = 1860,
  [SMALL_STATE(50)] = 1881,
  [SMALL_STATE(51)] = 1902,
  [SMALL_STATE(52)] = 1925,
  [SMALL_STATE(53)] = 1946,
  [SMALL_STATE(54)] = 1969,
  [SMALL_STATE(55)] = 1992,
  [SMALL_STATE(56)] = 2010,
  [SMALL_STATE(57)] = 2028,
  [SMALL_STATE(58)] = 2048,
  [SMALL_STATE(59)] = 2068,
  [SMALL_STATE(60)] = 2088,
  [SMALL_STATE(61)] = 2108,
  [SMALL_STATE(62)] = 2123,
  [SMALL_STATE(63)] = 2140,
  [SMALL_STATE(64)] = 2157,
  [SMALL_STATE(65)] = 2172,
  [SMALL_STATE(66)] = 2187,
  [SMALL_STATE(67)] = 2204,
  [SMALL_STATE(68)] = 2217,
  [SMALL_STATE(69)] = 2234,
  [SMALL_STATE(70)] = 2247,
  [SMALL_STATE(71)] = 2262,
  [SMALL_STATE(72)] = 2277,
  [SMALL_STATE(73)] = 2292,
  [SMALL_STATE(74)] = 2307,
  [SMALL_STATE(75)] = 2322,
  [SMALL_STATE(76)] = 2337,
  [SMALL_STATE(77)] = 2354,
  [SMALL_STATE(78)] = 2369,
  [SMALL_STATE(79)] = 2384,
  [SMALL_STATE(80)] = 2399,
  [SMALL_STATE(81)] = 2414,
  [SMALL_STATE(82)] = 2429,
  [SMALL_STATE(83)] = 2443,
  [SMALL_STATE(84)] = 2457,
  [SMALL_STATE(85)] = 2471,
  [SMALL_STATE(86)] = 2485,
  [SMALL_STATE(87)] = 2499,
  [SMALL_STATE(88)] = 2513,
  [SMALL_STATE(89)] = 2527,
  [SMALL_STATE(90)] = 2541,
  [SMALL_STATE(91)] = 2555,
  [SMALL_STATE(92)] = 2569,
  [SMALL_STATE(93)] = 2583,
  [SMALL_STATE(94)] = 2597,
  [SMALL_STATE(95)] = 2601,
  [SMALL_STATE(96)] = 2605,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(19),
  [60] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(91),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(27),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(87),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(27),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 11),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 12),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 19),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 20),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 20),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_rhs, 1, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 16),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(36),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(41),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(87),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(41),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 15),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 1, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expr, 1, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 2, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 2, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_lhs, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 23),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 23),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 28),
  [152] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 28),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 4, 0, 25),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_pattern, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_pattern, 2, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_pattern, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_pattern, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pattern, 1, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__pattern, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [176] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 4, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 1),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 2, 0, 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_declaration, 3, 0, 8),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_external_declaration, 3, 0, 8),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 6),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3, 0, 6),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 2, 0, 13), SHIFT_REPEAT(24),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 2, 0, 13),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [237] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [240] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [243] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 2, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 0),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 0), SHIFT_REPEAT(89),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 1, 0, 2),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [254] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [256] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 2, 0, 7),
  [262] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 4, 0, 26),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block_end, 2, 0, 14),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [274] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_comment_repeat1, 1, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 3, 0, 17),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 18),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 1, 0, 5),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 10),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 3, 0, 21),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 22),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block_end, 3, 0, 24),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 3),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 4),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 4, 0, 27),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 2, 0, 9),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_modifier, 1, 0, 0),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [314] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_refal5(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
