#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 74
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 7
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 8

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_EQ = 4,
  anon_sym_COMMA = 5,
  anon_sym_COLON = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LT = 9,
  anon_sym_GT = 10,
  anon_sym_DOT = 11,
  sym_ident = 12,
  anon_sym_s = 13,
  anon_sym_e = 14,
  anon_sym_t = 15,
  sym_string = 16,
  sym_number = 17,
  sym_entry_modifier = 18,
  anon_sym_DOLLAREXTERNAL = 19,
  anon_sym_DOLLAREXTERN = 20,
  anon_sym_DOLLAREXTRN = 21,
  sym_comment = 22,
  sym_source_file = 23,
  sym_external_declaration = 24,
  sym_function_name_list = 25,
  sym_function_definition = 26,
  sym_body = 27,
  sym_sentence = 28,
  sym_sentenceEq = 29,
  sym_sentenceBlock = 30,
  sym_sentenceBlockEnd = 31,
  aux_sym__pattern = 32,
  sym_condition = 33,
  aux_sym__expr = 34,
  sym_variable = 35,
  sym_type = 36,
  sym_external_modifier = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_function_name_list_repeat1 = 39,
  aux_sym_body_repeat1 = 40,
  aux_sym_sentenceEq_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [sym_ident] = "ident",
  [anon_sym_s] = "s",
  [anon_sym_e] = "e",
  [anon_sym_t] = "t",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_entry_modifier] = "entry_modifier",
  [anon_sym_DOLLAREXTERNAL] = "$EXTERNAL",
  [anon_sym_DOLLAREXTERN] = "$EXTERN",
  [anon_sym_DOLLAREXTRN] = "$EXTRN",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_external_declaration] = "external_declaration",
  [sym_function_name_list] = "function_name_list",
  [sym_function_definition] = "function_definition",
  [sym_body] = "body",
  [sym_sentence] = "sentence",
  [sym_sentenceEq] = "sentenceEq",
  [sym_sentenceBlock] = "sentenceBlock",
  [sym_sentenceBlockEnd] = "sentenceBlockEnd",
  [aux_sym__pattern] = "_pattern",
  [sym_condition] = "condition",
  [aux_sym__expr] = "_expr",
  [sym_variable] = "variable",
  [sym_type] = "type",
  [sym_external_modifier] = "external_modifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_name_list_repeat1] = "function_name_list_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_sentenceEq_repeat1] = "sentenceEq_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_ident] = sym_ident,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_t] = anon_sym_t,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_entry_modifier] = sym_entry_modifier,
  [anon_sym_DOLLAREXTERNAL] = anon_sym_DOLLAREXTERNAL,
  [anon_sym_DOLLAREXTERN] = anon_sym_DOLLAREXTERN,
  [anon_sym_DOLLAREXTRN] = anon_sym_DOLLAREXTRN,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_external_declaration] = sym_external_declaration,
  [sym_function_name_list] = sym_function_name_list,
  [sym_function_definition] = sym_function_definition,
  [sym_body] = sym_body,
  [sym_sentence] = sym_sentence,
  [sym_sentenceEq] = sym_sentenceEq,
  [sym_sentenceBlock] = sym_sentenceBlock,
  [sym_sentenceBlockEnd] = sym_sentenceBlockEnd,
  [aux_sym__pattern] = aux_sym__pattern,
  [sym_condition] = sym_condition,
  [aux_sym__expr] = aux_sym__expr,
  [sym_variable] = sym_variable,
  [sym_type] = sym_type,
  [sym_external_modifier] = sym_external_modifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_name_list_repeat1] = aux_sym_function_name_list_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_sentenceEq_repeat1] = aux_sym_sentenceEq_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_modifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAREXTERNAL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAREXTERN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAREXTRN] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_external_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_sentenceEq] = {
    .visible = true,
    .named = true,
  },
  [sym_sentenceBlock] = {
    .visible = true,
    .named = true,
  },
  [sym_sentenceBlockEnd] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pattern] = {
    .visible = false,
    .named = false,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__expr] = {
    .visible = false,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_external_modifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_name_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentenceEq_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_func_body = 1,
  field_func_name = 2,
  field_func_name_list = 3,
  field_name = 4,
  field_pattern = 5,
  field_result = 6,
  field_type = 7,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_func_body] = "func_body",
  [field_func_name] = "func_name",
  [field_func_name_list] = "func_name_list",
  [field_name] = "name",
  [field_pattern] = "pattern",
  [field_result] = "result",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 1},
  [4] = {.index = 5, .length = 1},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_func_body, 1},
    {field_func_name, 0},
  [2] =
    {field_func_body, 2},
    {field_func_name, 1},
  [4] =
    {field_func_name_list, 1},
  [5] =
    {field_pattern, 2},
  [6] =
    {field_result, 1},
  [7] =
    {field_name, 2},
    {field_type, 0},
  [9] =
    {field_pattern, 3},
    {field_result, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '"', 1,
        '$', 8,
        '\'', 2,
        '(', 28,
        ')', 29,
        ',', 26,
        '.', 32,
        '/', 5,
        ':', 27,
        ';', 22,
        '<', 30,
        '=', 25,
        '>', 31,
        'e', 36,
        's', 35,
        't', 37,
        '{', 23,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(45);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(15);
      if (lookahead == 'R') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'L') ADVANCE(41);
      END_STATE();
    case 11:
      if (lookahead == 'N') ADVANCE(16);
      if (lookahead == 'X') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'N') ADVANCE(43);
      END_STATE();
    case 13:
      if (lookahead == 'N') ADVANCE(42);
      END_STATE();
    case 14:
      if (lookahead == 'R') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'R') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'T') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 18:
      if (lookahead == 'Y') ADVANCE(40);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '$') ADVANCE(8);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '}') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_s);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_e);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_t);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_entry_modifier);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTERNAL);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTERN);
      if (lookahead == 'A') ADVANCE(10);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTRN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 20},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 20},
  [41] = {.lex_state = 20},
  [42] = {.lex_state = 20},
  [43] = {.lex_state = 20},
  [44] = {.lex_state = 20},
  [45] = {.lex_state = 20},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 20},
  [50] = {.lex_state = 20},
  [51] = {.lex_state = 20},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 20},
  [66] = {.lex_state = 20},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 20},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 20},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_entry_modifier] = ACTIONS(1),
    [anon_sym_DOLLAREXTERNAL] = ACTIONS(1),
    [anon_sym_DOLLAREXTERN] = ACTIONS(1),
    [anon_sym_DOLLAREXTRN] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(71),
    [sym_external_declaration] = STATE(36),
    [sym_function_definition] = STATE(36),
    [sym_external_modifier] = STATE(50),
    [aux_sym_source_file_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [sym_entry_modifier] = ACTIONS(9),
    [anon_sym_DOLLAREXTERNAL] = ACTIONS(11),
    [anon_sym_DOLLAREXTERN] = ACTIONS(13),
    [anon_sym_DOLLAREXTRN] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_EQ,
    ACTIONS(20), 1,
      anon_sym_COMMA,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 1,
      sym_string,
    STATE(2), 1,
      aux_sym_body_repeat1,
    STATE(63), 1,
      sym_sentence,
    STATE(69), 1,
      sym_type,
    ACTIONS(26), 2,
      sym_ident,
      sym_number,
    STATE(7), 2,
      aux_sym__pattern,
      sym_variable,
    STATE(48), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
    STATE(55), 2,
      sym_sentenceEq,
      sym_sentenceBlock,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [49] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    ACTIONS(37), 1,
      anon_sym_EQ,
    ACTIONS(39), 1,
      anon_sym_COMMA,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      sym_string,
    STATE(2), 1,
      aux_sym_body_repeat1,
    STATE(54), 1,
      sym_sentence,
    STATE(69), 1,
      sym_type,
    ACTIONS(43), 2,
      sym_ident,
      sym_number,
    STATE(7), 2,
      aux_sym__pattern,
      sym_variable,
    STATE(48), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
    STATE(55), 2,
      sym_sentenceEq,
      sym_sentenceBlock,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [98] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_EQ,
    ACTIONS(39), 1,
      anon_sym_COMMA,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      sym_string,
    STATE(3), 1,
      aux_sym_body_repeat1,
    STATE(63), 1,
      sym_sentence,
    STATE(69), 1,
      sym_type,
    ACTIONS(43), 2,
      sym_ident,
      sym_number,
    STATE(7), 2,
      aux_sym__pattern,
      sym_variable,
    STATE(48), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
    STATE(55), 2,
      sym_sentenceEq,
      sym_sentenceBlock,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [144] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_LT,
    ACTIONS(63), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(57), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(60), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(49), 5,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_GT,
  [180] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
    ACTIONS(66), 10,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [203] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(76), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(74), 2,
      sym_ident,
      sym_number,
    STATE(12), 2,
      aux_sym__pattern,
      sym_variable,
    STATE(47), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [239] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(86), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(78), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(84), 2,
      sym_ident,
      sym_number,
    STATE(19), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [272] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      anon_sym_COLON,
    ACTIONS(92), 1,
      sym_string,
    STATE(57), 1,
      sym_sentenceBlockEnd,
    STATE(69), 1,
      sym_type,
    ACTIONS(90), 2,
      sym_ident,
      sym_number,
    STATE(24), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [307] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    ACTIONS(100), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(96), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(98), 2,
      sym_ident,
      sym_number,
    STATE(27), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [340] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      anon_sym_COLON,
    ACTIONS(92), 1,
      sym_string,
    STATE(52), 1,
      sym_sentenceBlockEnd,
    STATE(69), 1,
      sym_type,
    ACTIONS(90), 2,
      sym_ident,
      sym_number,
    STATE(24), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [375] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(104), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(107), 2,
      sym_ident,
      sym_number,
    STATE(12), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(102), 3,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(110), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [406] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(120), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(116), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(118), 2,
      sym_ident,
      sym_number,
    STATE(16), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [439] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
    ACTIONS(49), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [460] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(124), 1,
      anon_sym_LBRACE,
    ACTIONS(130), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(126), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(128), 2,
      sym_ident,
      sym_number,
    STATE(31), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [493] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(136), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(132), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(134), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [526] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(140), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(132), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(138), 2,
      sym_ident,
      sym_number,
    STATE(22), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [559] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      anon_sym_COLON,
    ACTIONS(92), 1,
      sym_string,
    STATE(59), 1,
      sym_sentenceBlockEnd,
    STATE(69), 1,
      sym_type,
    ACTIONS(90), 2,
      sym_ident,
      sym_number,
    STATE(24), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [594] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(136), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(116), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(134), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [627] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(144), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
    ACTIONS(142), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [648] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
    ACTIONS(146), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [669] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(136), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(134), 2,
      sym_ident,
      sym_number,
    ACTIONS(150), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [702] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(152), 1,
      anon_sym_RPAREN,
    ACTIONS(156), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(154), 2,
      sym_ident,
      sym_number,
    STATE(25), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [734] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(136), 1,
      sym_string,
    ACTIONS(158), 1,
      anon_sym_COLON,
    STATE(69), 1,
      sym_type,
    ACTIONS(134), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [766] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(136), 1,
      sym_string,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      sym_type,
    ACTIONS(134), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [798] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(160), 1,
      anon_sym_GT,
    ACTIONS(164), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(162), 2,
      sym_ident,
      sym_number,
    STATE(29), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [830] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(74), 2,
      sym_ident,
      sym_number,
    ACTIONS(166), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    STATE(12), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [860] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_COLON,
    ACTIONS(172), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(170), 2,
      sym_ident,
      sym_number,
    STATE(32), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [892] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(136), 1,
      sym_string,
    ACTIONS(174), 1,
      anon_sym_GT,
    STATE(69), 1,
      sym_type,
    ACTIONS(134), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [924] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(100), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(96), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(98), 2,
      sym_ident,
      sym_number,
    STATE(27), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [954] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(74), 2,
      sym_ident,
      sym_number,
    ACTIONS(176), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    STATE(12), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [984] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(80), 1,
      anon_sym_LPAREN,
    ACTIONS(82), 1,
      anon_sym_LT,
    ACTIONS(136), 1,
      sym_string,
    ACTIONS(178), 1,
      anon_sym_COLON,
    STATE(69), 1,
      sym_type,
    ACTIONS(134), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1016] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(130), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(126), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(128), 2,
      sym_ident,
      sym_number,
    STATE(31), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1046] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      sym_string,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    STATE(69), 1,
      sym_type,
    ACTIONS(74), 2,
      sym_ident,
      sym_number,
    STATE(12), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1075] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    ACTIONS(186), 1,
      sym_string,
    STATE(69), 1,
      sym_type,
    ACTIONS(184), 2,
      sym_ident,
      sym_number,
    STATE(34), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1104] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(9), 1,
      sym_entry_modifier,
    ACTIONS(13), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(188), 1,
      ts_builtin_sym_end,
    STATE(50), 1,
      sym_external_modifier,
    ACTIONS(11), 2,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
    STATE(40), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1132] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 5,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      sym_string,
    ACTIONS(190), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
  [1150] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(192), 5,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(194), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
  [1168] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(102), 5,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(196), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
  [1186] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
    ACTIONS(200), 1,
      sym_ident,
    ACTIONS(203), 1,
      sym_entry_modifier,
    ACTIONS(209), 1,
      anon_sym_DOLLAREXTERN,
    STATE(50), 1,
      sym_external_modifier,
    ACTIONS(206), 2,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
    STATE(40), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1214] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(214), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(212), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1229] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(216), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1244] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(220), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1258] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(224), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1272] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(228), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1286] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_EQ,
    ACTIONS(234), 1,
      anon_sym_COMMA,
    STATE(46), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
  [1300] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(237), 1,
      anon_sym_EQ,
    ACTIONS(239), 1,
      anon_sym_COMMA,
    STATE(46), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
  [1314] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    STATE(46), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
  [1328] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(241), 1,
      anon_sym_SEMI,
    ACTIONS(243), 1,
      sym_ident,
    STATE(51), 1,
      aux_sym_function_name_list_repeat1,
  [1341] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      sym_ident,
    STATE(49), 1,
      aux_sym_function_name_list_repeat1,
    STATE(67), 1,
      sym_function_name_list,
  [1354] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_SEMI,
    ACTIONS(249), 1,
      sym_ident,
    STATE(51), 1,
      aux_sym_function_name_list_repeat1,
  [1367] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_body,
  [1385] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_SEMI,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
  [1395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1403] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
    STATE(43), 1,
      sym_body,
  [1413] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1421] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      sym_body,
  [1431] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1439] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1447] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 1,
      anon_sym_LBRACE,
    STATE(68), 1,
      sym_body,
  [1457] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_SEMI,
  [1472] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_DOT,
  [1479] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      sym_ident,
  [1486] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      sym_ident,
  [1493] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      anon_sym_SEMI,
  [1500] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_RBRACE,
  [1507] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      anon_sym_DOT,
  [1514] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      sym_ident,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      ts_builtin_sym_end,
  [1528] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      anon_sym_RBRACE,
  [1535] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      sym_ident,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 203,
  [SMALL_STATE(8)] = 239,
  [SMALL_STATE(9)] = 272,
  [SMALL_STATE(10)] = 307,
  [SMALL_STATE(11)] = 340,
  [SMALL_STATE(12)] = 375,
  [SMALL_STATE(13)] = 406,
  [SMALL_STATE(14)] = 439,
  [SMALL_STATE(15)] = 460,
  [SMALL_STATE(16)] = 493,
  [SMALL_STATE(17)] = 526,
  [SMALL_STATE(18)] = 559,
  [SMALL_STATE(19)] = 594,
  [SMALL_STATE(20)] = 627,
  [SMALL_STATE(21)] = 648,
  [SMALL_STATE(22)] = 669,
  [SMALL_STATE(23)] = 702,
  [SMALL_STATE(24)] = 734,
  [SMALL_STATE(25)] = 766,
  [SMALL_STATE(26)] = 798,
  [SMALL_STATE(27)] = 830,
  [SMALL_STATE(28)] = 860,
  [SMALL_STATE(29)] = 892,
  [SMALL_STATE(30)] = 924,
  [SMALL_STATE(31)] = 954,
  [SMALL_STATE(32)] = 984,
  [SMALL_STATE(33)] = 1016,
  [SMALL_STATE(34)] = 1046,
  [SMALL_STATE(35)] = 1075,
  [SMALL_STATE(36)] = 1104,
  [SMALL_STATE(37)] = 1132,
  [SMALL_STATE(38)] = 1150,
  [SMALL_STATE(39)] = 1168,
  [SMALL_STATE(40)] = 1186,
  [SMALL_STATE(41)] = 1214,
  [SMALL_STATE(42)] = 1229,
  [SMALL_STATE(43)] = 1244,
  [SMALL_STATE(44)] = 1258,
  [SMALL_STATE(45)] = 1272,
  [SMALL_STATE(46)] = 1286,
  [SMALL_STATE(47)] = 1300,
  [SMALL_STATE(48)] = 1314,
  [SMALL_STATE(49)] = 1328,
  [SMALL_STATE(50)] = 1341,
  [SMALL_STATE(51)] = 1354,
  [SMALL_STATE(52)] = 1367,
  [SMALL_STATE(53)] = 1375,
  [SMALL_STATE(54)] = 1385,
  [SMALL_STATE(55)] = 1395,
  [SMALL_STATE(56)] = 1403,
  [SMALL_STATE(57)] = 1413,
  [SMALL_STATE(58)] = 1421,
  [SMALL_STATE(59)] = 1431,
  [SMALL_STATE(60)] = 1439,
  [SMALL_STATE(61)] = 1447,
  [SMALL_STATE(62)] = 1457,
  [SMALL_STATE(63)] = 1465,
  [SMALL_STATE(64)] = 1472,
  [SMALL_STATE(65)] = 1479,
  [SMALL_STATE(66)] = 1486,
  [SMALL_STATE(67)] = 1493,
  [SMALL_STATE(68)] = 1500,
  [SMALL_STATE(69)] = 1507,
  [SMALL_STATE(70)] = 1514,
  [SMALL_STATE(71)] = 1521,
  [SMALL_STATE(72)] = 1528,
  [SMALL_STATE(73)] = 1535,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(23),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(66),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(5),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(64),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(5),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 6),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 6),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceEq, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(35),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(12),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(64),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(12),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceEq, 2, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 5),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceEq, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [138] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expr, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 4, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expr, 4, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceEq, 4, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 4),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 4, 0, 7),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pattern, 3, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__pattern, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [200] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [206] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [209] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(73),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 3, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 4, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 2),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3, 0, 2),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_declaration, 3, 0, 3),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_external_declaration, 3, 0, 3),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 1),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 2, 0, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentenceEq_repeat1, 2, 0, 0),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentenceEq_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 1, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 0),
  [249] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceBlock, 3, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceBlock, 2, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceBlock, 4, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceBlockEnd, 4, 0, 0),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceBlockEnd, 5, 0, 0),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [284] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_modifier, 1, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_refal5(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
