#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 75
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 42
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 11
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 21

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_EQ = 4,
  anon_sym_COMMA = 5,
  anon_sym_COLON = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LT = 9,
  anon_sym_GT = 10,
  anon_sym_DOT = 11,
  sym_ident = 12,
  anon_sym_s = 13,
  anon_sym_e = 14,
  anon_sym_t = 15,
  sym_string = 16,
  sym_number = 17,
  sym_entry_modifier = 18,
  anon_sym_DOLLAREXTERNAL = 19,
  anon_sym_DOLLAREXTERN = 20,
  anon_sym_DOLLAREXTRN = 21,
  sym_comment = 22,
  sym_source_file = 23,
  sym_external_declaration = 24,
  sym_function_name_list = 25,
  sym_function_definition = 26,
  sym_body = 27,
  sym_sentence = 28,
  sym_sentenceEq = 29,
  sym_sentenceBlock = 30,
  sym_sentenceBlockEnd = 31,
  aux_sym__pattern = 32,
  sym_condition = 33,
  aux_sym__expr = 34,
  sym_variable = 35,
  sym_type = 36,
  sym_external_modifier = 37,
  aux_sym_source_file_repeat1 = 38,
  aux_sym_function_name_list_repeat1 = 39,
  aux_sym_body_repeat1 = 40,
  aux_sym_sentenceEq_repeat1 = 41,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [sym_ident] = "ident",
  [anon_sym_s] = "s",
  [anon_sym_e] = "e",
  [anon_sym_t] = "t",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_entry_modifier] = "entry_modifier",
  [anon_sym_DOLLAREXTERNAL] = "$EXTERNAL",
  [anon_sym_DOLLAREXTERN] = "$EXTERN",
  [anon_sym_DOLLAREXTRN] = "$EXTRN",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_external_declaration] = "external_declaration",
  [sym_function_name_list] = "function_name_list",
  [sym_function_definition] = "function_definition",
  [sym_body] = "body",
  [sym_sentence] = "sentence",
  [sym_sentenceEq] = "sentenceEq",
  [sym_sentenceBlock] = "sentenceBlock",
  [sym_sentenceBlockEnd] = "sentenceBlockEnd",
  [aux_sym__pattern] = "_pattern",
  [sym_condition] = "condition",
  [aux_sym__expr] = "_expr",
  [sym_variable] = "variable",
  [sym_type] = "type",
  [sym_external_modifier] = "external_modifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_name_list_repeat1] = "function_name_list_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_sentenceEq_repeat1] = "sentenceEq_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_ident] = sym_ident,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_t] = anon_sym_t,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_entry_modifier] = sym_entry_modifier,
  [anon_sym_DOLLAREXTERNAL] = anon_sym_DOLLAREXTERNAL,
  [anon_sym_DOLLAREXTERN] = anon_sym_DOLLAREXTERN,
  [anon_sym_DOLLAREXTRN] = anon_sym_DOLLAREXTRN,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_external_declaration] = sym_external_declaration,
  [sym_function_name_list] = sym_function_name_list,
  [sym_function_definition] = sym_function_definition,
  [sym_body] = sym_body,
  [sym_sentence] = sym_sentence,
  [sym_sentenceEq] = sym_sentenceEq,
  [sym_sentenceBlock] = sym_sentenceBlock,
  [sym_sentenceBlockEnd] = sym_sentenceBlockEnd,
  [aux_sym__pattern] = aux_sym__pattern,
  [sym_condition] = sym_condition,
  [aux_sym__expr] = aux_sym__expr,
  [sym_variable] = sym_variable,
  [sym_type] = sym_type,
  [sym_external_modifier] = sym_external_modifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_name_list_repeat1] = aux_sym_function_name_list_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_sentenceEq_repeat1] = aux_sym_sentenceEq_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_modifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAREXTERNAL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAREXTERN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAREXTRN] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_external_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_sentenceEq] = {
    .visible = true,
    .named = true,
  },
  [sym_sentenceBlock] = {
    .visible = true,
    .named = true,
  },
  [sym_sentenceBlockEnd] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pattern] = {
    .visible = false,
    .named = false,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__expr] = {
    .visible = false,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_external_modifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_name_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentenceEq_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block = 1,
  field_body = 2,
  field_entry = 3,
  field_expr = 4,
  field_func_name_list = 5,
  field_lhs = 6,
  field_name = 7,
  field_pattern = 8,
  field_result = 9,
  field_rhs = 10,
  field_type = 11,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block] = "block",
  [field_body] = "body",
  [field_entry] = "entry",
  [field_expr] = "expr",
  [field_func_name_list] = "func_name_list",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_pattern] = "pattern",
  [field_result] = "result",
  [field_rhs] = "rhs",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 3},
  [5] = {.index = 7, .length = 1},
  [6] = {.index = 8, .length = 2},
  [7] = {.index = 10, .length = 1},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 1},
  [12] = {.index = 15, .length = 2},
  [13] = {.index = 17, .length = 1},
  [14] = {.index = 18, .length = 2},
  [15] = {.index = 20, .length = 2},
  [16] = {.index = 22, .length = 2},
  [17] = {.index = 24, .length = 3},
  [18] = {.index = 27, .length = 1},
  [19] = {.index = 28, .length = 1},
  [20] = {.index = 29, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
    {field_name, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_name, 0, .inherited = true},
  [4] =
    {field_body, 2},
    {field_entry, 0},
    {field_name, 1},
  [7] =
    {field_func_name_list, 1},
  [8] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [10] =
    {field_rhs, 1},
  [11] =
    {field_block, 1},
  [12] =
    {field_lhs, 0},
  [13] =
    {field_pattern, 2},
  [14] =
    {field_result, 1},
  [15] =
    {field_lhs, 0},
    {field_rhs, 2},
  [17] =
    {field_block, 2},
  [18] =
    {field_lhs, 0},
    {field_lhs, 1},
  [20] =
    {field_name, 2},
    {field_type, 0},
  [22] =
    {field_pattern, 3},
    {field_result, 1},
  [24] =
    {field_lhs, 0},
    {field_lhs, 1},
    {field_rhs, 3},
  [27] =
    {field_block, 3},
  [28] =
    {field_body, 2},
  [29] =
    {field_body, 3},
    {field_expr, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '"', 1,
        '$', 8,
        '\'', 2,
        '(', 28,
        ')', 29,
        ',', 26,
        '.', 32,
        '/', 5,
        ':', 27,
        ';', 22,
        '<', 30,
        '=', 25,
        '>', 31,
        'e', 36,
        's', 35,
        't', 37,
        '{', 23,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(19);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(45);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(44);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == 'E') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(15);
      if (lookahead == 'R') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'L') ADVANCE(41);
      END_STATE();
    case 11:
      if (lookahead == 'N') ADVANCE(16);
      if (lookahead == 'X') ADVANCE(17);
      END_STATE();
    case 12:
      if (lookahead == 'N') ADVANCE(43);
      END_STATE();
    case 13:
      if (lookahead == 'N') ADVANCE(42);
      END_STATE();
    case 14:
      if (lookahead == 'R') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'R') ADVANCE(13);
      END_STATE();
    case 16:
      if (lookahead == 'T') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 18:
      if (lookahead == 'Y') ADVANCE(40);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '$') ADVANCE(8);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '}') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_s);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_e);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_t);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_string);
      if (lookahead == '"') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_entry_modifier);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTERNAL);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTERN);
      if (lookahead == 'A') ADVANCE(10);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTRN);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(45);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 20},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 20},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 20},
  [42] = {.lex_state = 20},
  [43] = {.lex_state = 20},
  [44] = {.lex_state = 20},
  [45] = {.lex_state = 20},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 20},
  [50] = {.lex_state = 20},
  [51] = {.lex_state = 20},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 20},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 20},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 20},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 20},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 20},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_entry_modifier] = ACTIONS(1),
    [anon_sym_DOLLAREXTERNAL] = ACTIONS(1),
    [anon_sym_DOLLAREXTERN] = ACTIONS(1),
    [anon_sym_DOLLAREXTRN] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(64),
    [sym_external_declaration] = STATE(36),
    [sym_function_definition] = STATE(36),
    [sym_external_modifier] = STATE(51),
    [aux_sym_source_file_repeat1] = STATE(36),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [sym_entry_modifier] = ACTIONS(9),
    [anon_sym_DOLLAREXTERNAL] = ACTIONS(11),
    [anon_sym_DOLLAREXTERN] = ACTIONS(13),
    [anon_sym_DOLLAREXTRN] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_EQ,
    ACTIONS(19), 1,
      anon_sym_COMMA,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym_string,
    STATE(3), 1,
      aux_sym_body_repeat1,
    STATE(62), 1,
      sym_sentence,
    STATE(70), 1,
      sym_type,
    ACTIONS(23), 2,
      sym_ident,
      sym_number,
    STATE(7), 2,
      aux_sym__pattern,
      sym_variable,
    STATE(47), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
    STATE(55), 2,
      sym_sentenceEq,
      sym_sentenceBlock,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [49] = 14,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    ACTIONS(31), 1,
      anon_sym_EQ,
    ACTIONS(34), 1,
      anon_sym_COMMA,
    ACTIONS(37), 1,
      anon_sym_LPAREN,
    ACTIONS(46), 1,
      sym_string,
    STATE(3), 1,
      aux_sym_body_repeat1,
    STATE(68), 1,
      sym_sentence,
    STATE(70), 1,
      sym_type,
    ACTIONS(40), 2,
      sym_ident,
      sym_number,
    STATE(7), 2,
      aux_sym__pattern,
      sym_variable,
    STATE(47), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
    STATE(55), 2,
      sym_sentenceEq,
      sym_sentenceBlock,
    ACTIONS(43), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [98] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(17), 1,
      anon_sym_EQ,
    ACTIONS(19), 1,
      anon_sym_COMMA,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      sym_string,
    STATE(2), 1,
      aux_sym_body_repeat1,
    STATE(68), 1,
      sym_sentence,
    STATE(70), 1,
      sym_type,
    ACTIONS(23), 2,
      sym_ident,
      sym_number,
    STATE(7), 2,
      aux_sym__pattern,
      sym_variable,
    STATE(47), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
    STATE(55), 2,
      sym_sentenceEq,
      sym_sentenceBlock,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [144] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(54), 1,
      anon_sym_LT,
    ACTIONS(63), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(57), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(60), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(49), 5,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_GT,
  [180] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(68), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
    ACTIONS(66), 10,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [203] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    ACTIONS(76), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(74), 2,
      sym_ident,
      sym_number,
    STATE(13), 2,
      aux_sym__pattern,
      sym_variable,
    STATE(46), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [239] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(78), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
    ACTIONS(49), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [260] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(80), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [293] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(90), 1,
      anon_sym_LBRACE,
    ACTIONS(96), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(92), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(94), 2,
      sym_ident,
      sym_number,
    STATE(29), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [326] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(102), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(98), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(100), 2,
      sym_ident,
      sym_number,
    STATE(18), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [359] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(108), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(104), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(106), 2,
      sym_ident,
      sym_number,
    STATE(9), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [392] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 1,
      anon_sym_LPAREN,
    ACTIONS(121), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(115), 2,
      sym_ident,
      sym_number,
    STATE(13), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(110), 3,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(118), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [423] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(124), 1,
      anon_sym_COLON,
    ACTIONS(128), 1,
      sym_string,
    STATE(56), 1,
      sym_sentenceBlockEnd,
    STATE(70), 1,
      sym_type,
    ACTIONS(126), 2,
      sym_ident,
      sym_number,
    STATE(23), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [458] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(124), 1,
      anon_sym_COLON,
    ACTIONS(128), 1,
      sym_string,
    STATE(52), 1,
      sym_sentenceBlockEnd,
    STATE(70), 1,
      sym_type,
    ACTIONS(126), 2,
      sym_ident,
      sym_number,
    STATE(23), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [493] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(124), 1,
      anon_sym_COLON,
    ACTIONS(128), 1,
      sym_string,
    STATE(59), 1,
      sym_sentenceBlockEnd,
    STATE(70), 1,
      sym_type,
    ACTIONS(126), 2,
      sym_ident,
      sym_number,
    STATE(23), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [528] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(130), 1,
      anon_sym_LBRACE,
    ACTIONS(136), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(132), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(134), 2,
      sym_ident,
      sym_number,
    STATE(30), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [561] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    ACTIONS(138), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [594] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(144), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(140), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(142), 2,
      sym_ident,
      sym_number,
    STATE(21), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [627] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(148), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
    ACTIONS(146), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [648] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    ACTIONS(150), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [681] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
    ACTIONS(152), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [702] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      sym_string,
    ACTIONS(156), 1,
      anon_sym_COLON,
    STATE(70), 1,
      sym_type,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [734] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      sym_string,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      sym_type,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [766] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    ACTIONS(164), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(162), 2,
      sym_ident,
      sym_number,
    STATE(24), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [798] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(158), 1,
      anon_sym_GT,
    ACTIONS(168), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(166), 2,
      sym_ident,
      sym_number,
    STATE(31), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [830] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(170), 1,
      anon_sym_COLON,
    ACTIONS(174), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(172), 2,
      sym_ident,
      sym_number,
    STATE(32), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [862] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(96), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(92), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(94), 2,
      sym_ident,
      sym_number,
    STATE(29), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [892] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(74), 2,
      sym_ident,
      sym_number,
    ACTIONS(176), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    STATE(13), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [922] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(74), 2,
      sym_ident,
      sym_number,
    ACTIONS(178), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    STATE(13), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [952] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      sym_string,
    ACTIONS(180), 1,
      anon_sym_GT,
    STATE(70), 1,
      sym_type,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [984] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(82), 1,
      anon_sym_LPAREN,
    ACTIONS(84), 1,
      anon_sym_LT,
    ACTIONS(88), 1,
      sym_string,
    ACTIONS(182), 1,
      anon_sym_COLON,
    STATE(70), 1,
      sym_type,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    STATE(5), 2,
      aux_sym__expr,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1016] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(136), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(132), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(134), 2,
      sym_ident,
      sym_number,
    STATE(30), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1046] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(76), 1,
      sym_string,
    ACTIONS(184), 1,
      anon_sym_RPAREN,
    STATE(70), 1,
      sym_type,
    ACTIONS(74), 2,
      sym_ident,
      sym_number,
    STATE(13), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1075] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(190), 1,
      sym_string,
    STATE(70), 1,
      sym_type,
    ACTIONS(188), 2,
      sym_ident,
      sym_number,
    STATE(34), 2,
      aux_sym__pattern,
      sym_variable,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
  [1104] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(9), 1,
      sym_entry_modifier,
    ACTIONS(13), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(192), 1,
      ts_builtin_sym_end,
    STATE(51), 1,
      sym_external_modifier,
    ACTIONS(11), 2,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
    STATE(38), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1132] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(110), 5,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(194), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
  [1150] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      ts_builtin_sym_end,
    ACTIONS(198), 1,
      sym_ident,
    ACTIONS(201), 1,
      sym_entry_modifier,
    ACTIONS(207), 1,
      anon_sym_DOLLAREXTERN,
    STATE(51), 1,
      sym_external_modifier,
    ACTIONS(204), 2,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
    STATE(38), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1178] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(29), 5,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      sym_string,
    ACTIONS(210), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
  [1196] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(212), 5,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(214), 5,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
  [1214] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(216), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1229] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(220), 6,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1244] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(224), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1258] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(230), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(228), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1272] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(232), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1286] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_EQ,
    ACTIONS(238), 1,
      anon_sym_COMMA,
    STATE(48), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
  [1300] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_EQ,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    STATE(48), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
  [1314] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_EQ,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    STATE(48), 2,
      sym_condition,
      aux_sym_sentenceEq_repeat1,
  [1328] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(245), 1,
      anon_sym_SEMI,
    ACTIONS(247), 1,
      sym_ident,
    STATE(49), 1,
      aux_sym_function_name_list_repeat1,
  [1341] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(250), 1,
      anon_sym_SEMI,
    ACTIONS(252), 1,
      sym_ident,
    STATE(49), 1,
      aux_sym_function_name_list_repeat1,
  [1354] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      sym_ident,
    STATE(50), 1,
      aux_sym_function_name_list_repeat1,
    STATE(74), 1,
      sym_function_name_list,
  [1367] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1375] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_body,
  [1385] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      sym_body,
  [1395] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(258), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1403] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1411] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LBRACE,
    STATE(45), 1,
      sym_body,
  [1421] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LBRACE,
    STATE(73), 1,
      sym_body,
  [1431] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1439] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1447] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 2,
      anon_sym_SEMI,
      sym_ident,
  [1455] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_SEMI,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
  [1465] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1473] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 1,
      ts_builtin_sym_end,
  [1480] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 1,
      sym_ident,
  [1487] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 1,
      anon_sym_DOT,
  [1494] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_ident,
  [1501] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_SEMI,
  [1508] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 1,
      sym_ident,
  [1515] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 1,
      anon_sym_DOT,
  [1522] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 1,
      sym_ident,
  [1529] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 1,
      anon_sym_RBRACE,
  [1536] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 1,
      anon_sym_RBRACE,
  [1543] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 1,
      anon_sym_SEMI,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 49,
  [SMALL_STATE(4)] = 98,
  [SMALL_STATE(5)] = 144,
  [SMALL_STATE(6)] = 180,
  [SMALL_STATE(7)] = 203,
  [SMALL_STATE(8)] = 239,
  [SMALL_STATE(9)] = 260,
  [SMALL_STATE(10)] = 293,
  [SMALL_STATE(11)] = 326,
  [SMALL_STATE(12)] = 359,
  [SMALL_STATE(13)] = 392,
  [SMALL_STATE(14)] = 423,
  [SMALL_STATE(15)] = 458,
  [SMALL_STATE(16)] = 493,
  [SMALL_STATE(17)] = 528,
  [SMALL_STATE(18)] = 561,
  [SMALL_STATE(19)] = 594,
  [SMALL_STATE(20)] = 627,
  [SMALL_STATE(21)] = 648,
  [SMALL_STATE(22)] = 681,
  [SMALL_STATE(23)] = 702,
  [SMALL_STATE(24)] = 734,
  [SMALL_STATE(25)] = 766,
  [SMALL_STATE(26)] = 798,
  [SMALL_STATE(27)] = 830,
  [SMALL_STATE(28)] = 862,
  [SMALL_STATE(29)] = 892,
  [SMALL_STATE(30)] = 922,
  [SMALL_STATE(31)] = 952,
  [SMALL_STATE(32)] = 984,
  [SMALL_STATE(33)] = 1016,
  [SMALL_STATE(34)] = 1046,
  [SMALL_STATE(35)] = 1075,
  [SMALL_STATE(36)] = 1104,
  [SMALL_STATE(37)] = 1132,
  [SMALL_STATE(38)] = 1150,
  [SMALL_STATE(39)] = 1178,
  [SMALL_STATE(40)] = 1196,
  [SMALL_STATE(41)] = 1214,
  [SMALL_STATE(42)] = 1229,
  [SMALL_STATE(43)] = 1244,
  [SMALL_STATE(44)] = 1258,
  [SMALL_STATE(45)] = 1272,
  [SMALL_STATE(46)] = 1286,
  [SMALL_STATE(47)] = 1300,
  [SMALL_STATE(48)] = 1314,
  [SMALL_STATE(49)] = 1328,
  [SMALL_STATE(50)] = 1341,
  [SMALL_STATE(51)] = 1354,
  [SMALL_STATE(52)] = 1367,
  [SMALL_STATE(53)] = 1375,
  [SMALL_STATE(54)] = 1385,
  [SMALL_STATE(55)] = 1395,
  [SMALL_STATE(56)] = 1403,
  [SMALL_STATE(57)] = 1411,
  [SMALL_STATE(58)] = 1421,
  [SMALL_STATE(59)] = 1431,
  [SMALL_STATE(60)] = 1439,
  [SMALL_STATE(61)] = 1447,
  [SMALL_STATE(62)] = 1455,
  [SMALL_STATE(63)] = 1465,
  [SMALL_STATE(64)] = 1473,
  [SMALL_STATE(65)] = 1480,
  [SMALL_STATE(66)] = 1487,
  [SMALL_STATE(67)] = 1494,
  [SMALL_STATE(68)] = 1501,
  [SMALL_STATE(69)] = 1508,
  [SMALL_STATE(70)] = 1515,
  [SMALL_STATE(71)] = 1522,
  [SMALL_STATE(72)] = 1529,
  [SMALL_STATE(73)] = 1536,
  [SMALL_STATE(74)] = 1543,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(66),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(25),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(67),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(5),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(66),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(5),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 15),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 15),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceEq, 2, 0, 7),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceEq, 2, 0, 9),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceEq, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(35),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(13),
  [118] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(66),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(13),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 11),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceEq, 3, 0, 12),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceEq, 3, 0, 14),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [146] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expr, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceEq, 4, 0, 17),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 4, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__expr, 4, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 10),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 4, 0, 16),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [204] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [207] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pattern, 3, 0, 0),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__pattern, 3, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 4, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 3, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_declaration, 3, 0, 5),
  [226] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_external_declaration, 3, 0, 5),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 1),
  [230] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 2, 0, 1),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 4),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3, 0, 4),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentenceEq_repeat1, 2, 0, 0),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentenceEq_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 6),
  [247] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 6), SHIFT_REPEAT(61),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 1, 0, 3),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceBlock, 2, 0, 8),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceBlock, 3, 0, 13),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceBlock, 4, 0, 18),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceBlockEnd, 4, 0, 19),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 1, 0, 2),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentenceBlockEnd, 5, 0, 20),
  [274] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_modifier, 1, 0, 0),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_refal5(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
