#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 95
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 29

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_COMMA = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_EQ = 5,
  anon_sym_COLON = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LT = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_STAR = 12,
  anon_sym_SLASH = 13,
  anon_sym_GT = 14,
  anon_sym_DOT = 15,
  sym_ident = 16,
  anon_sym_s = 17,
  anon_sym_e = 18,
  anon_sym_t = 19,
  aux_sym_string_token1 = 20,
  anon_sym_BSLASH_BSLASH = 21,
  anon_sym_BSLASH_DQUOTE = 22,
  aux_sym_string_token2 = 23,
  sym_number = 24,
  aux_sym_symbols_token1 = 25,
  anon_sym_BSLASH_SQUOTE = 26,
  aux_sym_symbols_token2 = 27,
  sym_entry_modifier = 28,
  sym_external_modifier = 29,
  sym_comment = 30,
  sym_line_comment = 31,
  sym_source_file = 32,
  sym_external_declaration = 33,
  sym_function_name_list = 34,
  sym_function_definition = 35,
  sym_body = 36,
  sym_sentence = 37,
  sym_sentence_eq = 38,
  sym_sentence_block = 39,
  sym_sentence_lhs = 40,
  sym_sentence_rhs = 41,
  sym_sentence_block_end = 42,
  aux_sym__pattern = 43,
  sym_grouped_pattern = 44,
  sym_condition = 45,
  aux_sym__expr = 46,
  sym_function_call = 47,
  sym_grouped_expr = 48,
  sym_variable = 49,
  sym_type = 50,
  sym_string = 51,
  sym_symbols = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_function_name_list_repeat1 = 54,
  aux_sym_body_repeat1 = 55,
  aux_sym_sentence_eq_repeat1 = 56,
  aux_sym_string_repeat1 = 57,
  aux_sym_string_repeat2 = 58,
  aux_sym_symbols_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [sym_ident] = "ident",
  [anon_sym_s] = "s",
  [anon_sym_e] = "e",
  [anon_sym_t] = "t",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [aux_sym_string_token2] = "string_token2",
  [sym_number] = "number",
  [aux_sym_symbols_token1] = "symbols_token1",
  [anon_sym_BSLASH_SQUOTE] = "\\'",
  [aux_sym_symbols_token2] = "symbols_token2",
  [sym_entry_modifier] = "entry_modifier",
  [sym_external_modifier] = "external_modifier",
  [sym_comment] = "comment",
  [sym_line_comment] = "line_comment",
  [sym_source_file] = "source_file",
  [sym_external_declaration] = "external_declaration",
  [sym_function_name_list] = "function_name_list",
  [sym_function_definition] = "function_definition",
  [sym_body] = "body",
  [sym_sentence] = "sentence",
  [sym_sentence_eq] = "sentence_eq",
  [sym_sentence_block] = "sentence_block",
  [sym_sentence_lhs] = "sentence_lhs",
  [sym_sentence_rhs] = "sentence_rhs",
  [sym_sentence_block_end] = "sentence_block_end",
  [aux_sym__pattern] = "_pattern",
  [sym_grouped_pattern] = "grouped_pattern",
  [sym_condition] = "condition",
  [aux_sym__expr] = "_expr",
  [sym_function_call] = "function_call",
  [sym_grouped_expr] = "grouped_expr",
  [sym_variable] = "variable",
  [sym_type] = "type",
  [sym_string] = "string",
  [sym_symbols] = "symbols",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_name_list_repeat1] = "function_name_list_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_sentence_eq_repeat1] = "sentence_eq_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym_symbols_repeat1] = "symbols_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_ident] = sym_ident,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_t] = anon_sym_t,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_number] = sym_number,
  [aux_sym_symbols_token1] = aux_sym_symbols_token1,
  [anon_sym_BSLASH_SQUOTE] = anon_sym_BSLASH_SQUOTE,
  [aux_sym_symbols_token2] = aux_sym_symbols_token2,
  [sym_entry_modifier] = sym_entry_modifier,
  [sym_external_modifier] = sym_external_modifier,
  [sym_comment] = sym_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_source_file] = sym_source_file,
  [sym_external_declaration] = sym_external_declaration,
  [sym_function_name_list] = sym_function_name_list,
  [sym_function_definition] = sym_function_definition,
  [sym_body] = sym_body,
  [sym_sentence] = sym_sentence,
  [sym_sentence_eq] = sym_sentence_eq,
  [sym_sentence_block] = sym_sentence_block,
  [sym_sentence_lhs] = sym_sentence_lhs,
  [sym_sentence_rhs] = sym_sentence_rhs,
  [sym_sentence_block_end] = sym_sentence_block_end,
  [aux_sym__pattern] = aux_sym__pattern,
  [sym_grouped_pattern] = sym_grouped_pattern,
  [sym_condition] = sym_condition,
  [aux_sym__expr] = aux_sym__expr,
  [sym_function_call] = sym_function_call,
  [sym_grouped_expr] = sym_grouped_expr,
  [sym_variable] = sym_variable,
  [sym_type] = sym_type,
  [sym_string] = sym_string,
  [sym_symbols] = sym_symbols,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_name_list_repeat1] = aux_sym_function_name_list_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_sentence_eq_repeat1] = aux_sym_sentence_eq_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym_symbols_repeat1] = aux_sym_symbols_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_symbols_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_symbols_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_entry_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_external_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_external_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_block] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_lhs] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_rhs] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_block_end] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pattern] = {
    .visible = false,
    .named = false,
  },
  [sym_grouped_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__expr] = {
    .visible = false,
    .named = false,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_symbols] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_name_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_eq_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_symbols_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block = 1,
  field_body = 2,
  field_condition = 3,
  field_entry = 4,
  field_expr = 5,
  field_func_name_list = 6,
  field_lhs = 7,
  field_name = 8,
  field_param = 9,
  field_pattern = 10,
  field_result = 11,
  field_rhs = 12,
  field_sentence_block = 13,
  field_sentence_eq = 14,
  field_type = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block] = "block",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_entry] = "entry",
  [field_expr] = "expr",
  [field_func_name_list] = "func_name_list",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_param] = "param",
  [field_pattern] = "pattern",
  [field_result] = "result",
  [field_rhs] = "rhs",
  [field_sentence_block] = "sentence_block",
  [field_sentence_eq] = "sentence_eq",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 3},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 1},
  [12] = {.index = 15, .length = 1},
  [13] = {.index = 16, .length = 2},
  [14] = {.index = 18, .length = 1},
  [15] = {.index = 19, .length = 1},
  [16] = {.index = 20, .length = 1},
  [17] = {.index = 21, .length = 2},
  [18] = {.index = 23, .length = 2},
  [19] = {.index = 25, .length = 2},
  [20] = {.index = 27, .length = 2},
  [21] = {.index = 29, .length = 2},
  [22] = {.index = 31, .length = 2},
  [23] = {.index = 33, .length = 1},
  [24] = {.index = 34, .length = 2},
  [25] = {.index = 36, .length = 2},
  [26] = {.index = 38, .length = 3},
  [27] = {.index = 41, .length = 3},
  [28] = {.index = 44, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
    {field_name, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_sentence_eq, 0},
  [4] =
    {field_sentence_block, 0},
  [5] =
    {field_condition, 0},
  [6] =
    {field_body, 2},
    {field_entry, 0},
    {field_name, 1},
  [9] =
    {field_name, 0},
    {field_name, 1},
  [11] =
    {field_func_name_list, 1},
  [12] =
    {field_block, 1},
  [13] =
    {field_rhs, 1},
  [14] =
    {field_lhs, 0},
  [15] =
    {field_condition, 0, .inherited = true},
  [16] =
    {field_condition, 0, .inherited = true},
    {field_condition, 1, .inherited = true},
  [18] =
    {field_body, 1},
  [19] =
    {field_pattern, 2},
  [20] =
    {field_result, 1},
  [21] =
    {field_block, 2},
    {field_lhs, 0},
  [23] =
    {field_lhs, 0},
    {field_rhs, 2},
  [25] =
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
  [27] =
    {field_name, 2},
    {field_type, 0},
  [29] =
    {field_block, 2},
    {field_condition, 0, .inherited = true},
  [31] =
    {field_condition, 0, .inherited = true},
    {field_rhs, 2},
  [33] =
    {field_name, 1},
  [34] =
    {field_body, 2},
    {field_expr, 0},
  [36] =
    {field_pattern, 3},
    {field_result, 1},
  [38] =
    {field_block, 3},
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
  [41] =
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
    {field_rhs, 3},
  [44] =
    {field_name, 1},
    {field_param, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 55,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 45,
        '$', 11,
        '\'', 53,
        '(', 31,
        ')', 32,
        '*', 36,
        '+', 34,
        ',', 26,
        '-', 35,
        '.', 39,
        '/', 37,
        ':', 30,
        ';', 25,
        '<', 33,
        '=', 29,
        '>', 38,
        '\\', 4,
        'e', 43,
        's', 42,
        't', 44,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead == '\\') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\'') ADVANCE(52);
      if (lookahead == '*') ADVANCE(55);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 45,
        '\'', 53,
        '(', 31,
        ')', 32,
        '*', 62,
        ',', 26,
        '/', 8,
        ':', 30,
        ';', 25,
        '<', 33,
        '=', 29,
        '>', 38,
        'e', 43,
        's', 42,
        't', 44,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(46);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '+') ADVANCE(34);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '/') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(10);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(61);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(18);
      if (lookahead == 'R') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'L') ADVANCE(59);
      END_STATE();
    case 14:
      if (lookahead == 'N') ADVANCE(19);
      if (lookahead == 'X') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'N') ADVANCE(59);
      END_STATE();
    case 16:
      if (lookahead == 'N') ADVANCE(60);
      END_STATE();
    case 17:
      if (lookahead == 'R') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'R') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'T') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'T') ADVANCE(12);
      END_STATE();
    case 21:
      if (lookahead == 'Y') ADVANCE(58);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '$', 11,
        '*', 62,
        ',', 26,
        '.', 39,
        '/', 8,
        ';', 25,
        '=', 29,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_s);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_e);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_t);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\\') ADVANCE(46);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(48);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_symbols_token1);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_symbols_token1);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BSLASH_SQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_symbols_token2);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_symbols_token2);
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(46);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_symbols_token2);
      if (lookahead == '*') ADVANCE(55);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'') ADVANCE(55);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entry_modifier);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_external_modifier);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_external_modifier);
      if (lookahead == 'A') ADVANCE(13);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 23},
  [45] = {.lex_state = 23},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 23},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 23},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 23},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 7},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 23},
  [59] = {.lex_state = 23},
  [60] = {.lex_state = 23},
  [61] = {.lex_state = 23},
  [62] = {.lex_state = 23},
  [63] = {.lex_state = 23},
  [64] = {.lex_state = 23},
  [65] = {.lex_state = 23},
  [66] = {.lex_state = 23},
  [67] = {.lex_state = 23},
  [68] = {.lex_state = 23},
  [69] = {.lex_state = 23},
  [70] = {.lex_state = 23},
  [71] = {.lex_state = 23},
  [72] = {.lex_state = 23},
  [73] = {.lex_state = 23},
  [74] = {.lex_state = 23},
  [75] = {.lex_state = 23},
  [76] = {.lex_state = 23},
  [77] = {.lex_state = 23},
  [78] = {.lex_state = 23},
  [79] = {.lex_state = 23},
  [80] = {.lex_state = 23},
  [81] = {.lex_state = 23},
  [82] = {.lex_state = 23},
  [83] = {.lex_state = 23},
  [84] = {.lex_state = 23},
  [85] = {.lex_state = 23},
  [86] = {.lex_state = 23},
  [87] = {.lex_state = 23},
  [88] = {.lex_state = 23},
  [89] = {.lex_state = 23},
  [90] = {.lex_state = 23},
  [91] = {.lex_state = 23},
  [92] = {.lex_state = 23},
  [93] = {.lex_state = 23},
  [94] = {.lex_state = 23},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_symbols_token1] = ACTIONS(1),
    [anon_sym_BSLASH_SQUOTE] = ACTIONS(1),
    [sym_entry_modifier] = ACTIONS(1),
    [sym_external_modifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(93),
    [sym_external_declaration] = STATE(44),
    [sym_function_definition] = STATE(44),
    [aux_sym_source_file_repeat1] = STATE(44),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [sym_entry_modifier] = ACTIONS(9),
    [sym_external_modifier] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 18,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    STATE(3), 1,
      aux_sym_body_repeat1,
    STATE(58), 1,
      sym_sentence_lhs,
    STATE(63), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(71), 1,
      sym_sentence_eq,
    STATE(72), 1,
      sym_condition,
    STATE(78), 1,
      sym_sentence_block,
    STATE(81), 1,
      sym_sentence,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(23), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(25), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [63] = 18,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(19), 1,
      anon_sym_EQ,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(4), 1,
      aux_sym_body_repeat1,
    STATE(58), 1,
      sym_sentence_lhs,
    STATE(63), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(70), 1,
      sym_sentence,
    STATE(71), 1,
      sym_sentence_eq,
    STATE(72), 1,
      sym_condition,
    STATE(78), 1,
      sym_sentence_block,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(23), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(25), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [126] = 18,
    ACTIONS(33), 1,
      anon_sym_COMMA,
    ACTIONS(36), 1,
      anon_sym_RBRACE,
    ACTIONS(38), 1,
      anon_sym_EQ,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(50), 1,
      aux_sym_string_token1,
    ACTIONS(53), 1,
      aux_sym_symbols_token1,
    STATE(4), 1,
      aux_sym_body_repeat1,
    STATE(58), 1,
      sym_sentence_lhs,
    STATE(63), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(71), 1,
      sym_sentence_eq,
    STATE(72), 1,
      sym_condition,
    STATE(78), 1,
      sym_sentence_block,
    STATE(89), 1,
      sym_type,
    STATE(90), 1,
      sym_sentence,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(44), 2,
      sym_ident,
      sym_number,
    ACTIONS(47), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(25), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [189] = 10,
    ACTIONS(58), 1,
      anon_sym_LPAREN,
    ACTIONS(61), 1,
      anon_sym_LT,
    ACTIONS(70), 1,
      aux_sym_string_token1,
    ACTIONS(73), 1,
      aux_sym_symbols_token1,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(64), 2,
      sym_ident,
      sym_number,
    ACTIONS(67), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(56), 5,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_GT,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [233] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    STATE(84), 1,
      sym_sentence_rhs,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(76), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(82), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [277] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    STATE(69), 1,
      sym_sentence_rhs,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(82), 2,
      sym_ident,
      sym_number,
    ACTIONS(84), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [321] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    STATE(74), 1,
      sym_sentence_rhs,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(82), 2,
      sym_ident,
      sym_number,
    ACTIONS(86), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [365] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    STATE(83), 1,
      sym_sentence_rhs,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(82), 2,
      sym_ident,
      sym_number,
    ACTIONS(88), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [409] = 11,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(77), 1,
      sym_body,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(90), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(94), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(28), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [452] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(96), 1,
      anon_sym_COLON,
    STATE(79), 1,
      sym_sentence_block_end,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(98), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(18), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [495] = 10,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(100), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(102), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [536] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(96), 1,
      anon_sym_COLON,
    STATE(73), 1,
      sym_sentence_block_end,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(98), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(18), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [579] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(96), 1,
      anon_sym_COLON,
    STATE(75), 1,
      sym_sentence_block_end,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(98), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(18), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [622] = 11,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(76), 1,
      sym_body,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(104), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(106), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(32), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [665] = 11,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(96), 1,
      anon_sym_COLON,
    STATE(80), 1,
      sym_sentence_block_end,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(98), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(18), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [708] = 9,
    ACTIONS(110), 1,
      anon_sym_LPAREN,
    ACTIONS(119), 1,
      aux_sym_string_token1,
    ACTIONS(122), 1,
      aux_sym_symbols_token1,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(113), 2,
      sym_ident,
      sym_number,
    ACTIONS(108), 3,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_RPAREN,
    ACTIONS(116), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [746] = 10,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(125), 1,
      anon_sym_COLON,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(102), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [786] = 10,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(129), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(20), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [826] = 10,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(131), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(102), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [866] = 10,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(133), 1,
      anon_sym_GT,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(135), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(23), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [906] = 10,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(137), 1,
      anon_sym_COLON,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(139), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(24), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [946] = 10,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(141), 1,
      anon_sym_GT,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(102), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [986] = 10,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(78), 1,
      anon_sym_LPAREN,
    ACTIONS(80), 1,
      anon_sym_LT,
    ACTIONS(143), 1,
      anon_sym_COLON,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(102), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [1026] = 9,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(145), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(147), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1063] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(151), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(149), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1088] = 9,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(104), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(106), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(32), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1125] = 9,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(147), 2,
      sym_ident,
      sym_number,
    ACTIONS(153), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1162] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(157), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(155), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1187] = 9,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(90), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(94), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(28), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1224] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(161), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(159), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1249] = 9,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(147), 2,
      sym_ident,
      sym_number,
    ACTIONS(163), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1286] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(167), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(165), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1311] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(171), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(169), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1336] = 9,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(173), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(147), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1372] = 9,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(27), 1,
      aux_sym_string_token1,
    ACTIONS(29), 1,
      aux_sym_symbols_token1,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(177), 2,
      sym_ident,
      sym_number,
    ACTIONS(25), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(35), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1408] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(181), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(179), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1431] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(185), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(183), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1454] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(189), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(187), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1477] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(193), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(191), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1500] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(195), 5,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_string_token1,
    ACTIONS(197), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
  [1520] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(36), 5,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_LPAREN,
      aux_sym_string_token1,
    ACTIONS(199), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
  [1540] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(201), 5,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_string_token1,
    ACTIONS(203), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
  [1560] = 6,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(9), 1,
      sym_entry_modifier,
    ACTIONS(11), 1,
      sym_external_modifier,
    ACTIONS(205), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    STATE(45), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1582] = 6,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
    ACTIONS(209), 1,
      sym_ident,
    ACTIONS(212), 1,
      sym_entry_modifier,
    ACTIONS(215), 1,
      sym_external_modifier,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    STATE(45), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1604] = 4,
    ACTIONS(218), 1,
      aux_sym_string_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(53), 2,
      aux_sym_string_repeat1,
      aux_sym_string_repeat2,
    ACTIONS(220), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1621] = 4,
    ACTIONS(225), 1,
      aux_sym_symbols_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(47), 2,
      aux_sym_string_repeat1,
      aux_sym_symbols_repeat1,
    ACTIONS(222), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1638] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(227), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1651] = 4,
    ACTIONS(231), 1,
      aux_sym_symbols_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(47), 2,
      aux_sym_string_repeat1,
      aux_sym_symbols_repeat1,
    ACTIONS(229), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1668] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(233), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1681] = 4,
    ACTIONS(235), 1,
      aux_sym_string_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(51), 2,
      aux_sym_string_repeat1,
      aux_sym_string_repeat2,
    ACTIONS(237), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1698] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(240), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1711] = 4,
    ACTIONS(242), 1,
      aux_sym_string_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(51), 2,
      aux_sym_string_repeat1,
      aux_sym_string_repeat2,
    ACTIONS(244), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1728] = 4,
    ACTIONS(248), 1,
      aux_sym_symbols_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(49), 2,
      aux_sym_string_repeat1,
      aux_sym_symbols_repeat1,
    ACTIONS(246), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1745] = 4,
    ACTIONS(252), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(55), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(250), 3,
      aux_sym_string_token1,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1761] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(255), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_ident,
  [1773] = 4,
    ACTIONS(257), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(57), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(250), 3,
      aux_sym_symbols_token1,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1789] = 5,
    ACTIONS(260), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_EQ,
    STATE(60), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(72), 1,
      sym_condition,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1806] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(264), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1817] = 5,
    ACTIONS(266), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_EQ,
    STATE(64), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(72), 1,
      sym_condition,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1834] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(270), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1845] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(272), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1856] = 5,
    ACTIONS(274), 1,
      anon_sym_COMMA,
    ACTIONS(276), 1,
      anon_sym_EQ,
    STATE(64), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(72), 1,
      sym_condition,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1873] = 5,
    ACTIONS(278), 1,
      anon_sym_COMMA,
    ACTIONS(281), 1,
      anon_sym_EQ,
    STATE(64), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(72), 1,
      sym_condition,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1890] = 4,
    ACTIONS(283), 1,
      anon_sym_SEMI,
    ACTIONS(285), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_function_name_list_repeat1,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1904] = 4,
    ACTIONS(287), 1,
      anon_sym_SEMI,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    STATE(66), 1,
      aux_sym_function_name_list_repeat1,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1918] = 4,
    ACTIONS(285), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_SEMI,
    STATE(65), 1,
      aux_sym_function_name_list_repeat1,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1932] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(287), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [1941] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(294), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1950] = 3,
    ACTIONS(296), 1,
      anon_sym_SEMI,
    ACTIONS(298), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1961] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(300), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1970] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(302), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
  [1979] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(304), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1988] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(306), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1997] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(308), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2006] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(310), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2015] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(312), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2024] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(314), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2033] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(316), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2042] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(318), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2051] = 3,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    ACTIONS(296), 1,
      anon_sym_SEMI,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2062] = 3,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym_body,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2073] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(320), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2082] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(322), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2091] = 3,
    ACTIONS(92), 1,
      anon_sym_LBRACE,
    STATE(61), 1,
      sym_body,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2102] = 3,
    ACTIONS(324), 1,
      sym_ident,
    STATE(87), 1,
      sym_function_name_list,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2113] = 2,
    ACTIONS(326), 1,
      anon_sym_SEMI,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2121] = 2,
    ACTIONS(328), 1,
      anon_sym_DOT,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2129] = 2,
    ACTIONS(330), 1,
      anon_sym_DOT,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2137] = 2,
    ACTIONS(296), 1,
      anon_sym_SEMI,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2145] = 2,
    ACTIONS(332), 1,
      sym_ident,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2153] = 2,
    ACTIONS(334), 1,
      sym_ident,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2161] = 2,
    ACTIONS(336), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2169] = 2,
    ACTIONS(338), 1,
      sym_ident,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 63,
  [SMALL_STATE(4)] = 126,
  [SMALL_STATE(5)] = 189,
  [SMALL_STATE(6)] = 233,
  [SMALL_STATE(7)] = 277,
  [SMALL_STATE(8)] = 321,
  [SMALL_STATE(9)] = 365,
  [SMALL_STATE(10)] = 409,
  [SMALL_STATE(11)] = 452,
  [SMALL_STATE(12)] = 495,
  [SMALL_STATE(13)] = 536,
  [SMALL_STATE(14)] = 579,
  [SMALL_STATE(15)] = 622,
  [SMALL_STATE(16)] = 665,
  [SMALL_STATE(17)] = 708,
  [SMALL_STATE(18)] = 746,
  [SMALL_STATE(19)] = 786,
  [SMALL_STATE(20)] = 826,
  [SMALL_STATE(21)] = 866,
  [SMALL_STATE(22)] = 906,
  [SMALL_STATE(23)] = 946,
  [SMALL_STATE(24)] = 986,
  [SMALL_STATE(25)] = 1026,
  [SMALL_STATE(26)] = 1063,
  [SMALL_STATE(27)] = 1088,
  [SMALL_STATE(28)] = 1125,
  [SMALL_STATE(29)] = 1162,
  [SMALL_STATE(30)] = 1187,
  [SMALL_STATE(31)] = 1224,
  [SMALL_STATE(32)] = 1249,
  [SMALL_STATE(33)] = 1286,
  [SMALL_STATE(34)] = 1311,
  [SMALL_STATE(35)] = 1336,
  [SMALL_STATE(36)] = 1372,
  [SMALL_STATE(37)] = 1408,
  [SMALL_STATE(38)] = 1431,
  [SMALL_STATE(39)] = 1454,
  [SMALL_STATE(40)] = 1477,
  [SMALL_STATE(41)] = 1500,
  [SMALL_STATE(42)] = 1520,
  [SMALL_STATE(43)] = 1540,
  [SMALL_STATE(44)] = 1560,
  [SMALL_STATE(45)] = 1582,
  [SMALL_STATE(46)] = 1604,
  [SMALL_STATE(47)] = 1621,
  [SMALL_STATE(48)] = 1638,
  [SMALL_STATE(49)] = 1651,
  [SMALL_STATE(50)] = 1668,
  [SMALL_STATE(51)] = 1681,
  [SMALL_STATE(52)] = 1698,
  [SMALL_STATE(53)] = 1711,
  [SMALL_STATE(54)] = 1728,
  [SMALL_STATE(55)] = 1745,
  [SMALL_STATE(56)] = 1761,
  [SMALL_STATE(57)] = 1773,
  [SMALL_STATE(58)] = 1789,
  [SMALL_STATE(59)] = 1806,
  [SMALL_STATE(60)] = 1817,
  [SMALL_STATE(61)] = 1834,
  [SMALL_STATE(62)] = 1845,
  [SMALL_STATE(63)] = 1856,
  [SMALL_STATE(64)] = 1873,
  [SMALL_STATE(65)] = 1890,
  [SMALL_STATE(66)] = 1904,
  [SMALL_STATE(67)] = 1918,
  [SMALL_STATE(68)] = 1932,
  [SMALL_STATE(69)] = 1941,
  [SMALL_STATE(70)] = 1950,
  [SMALL_STATE(71)] = 1961,
  [SMALL_STATE(72)] = 1970,
  [SMALL_STATE(73)] = 1979,
  [SMALL_STATE(74)] = 1988,
  [SMALL_STATE(75)] = 1997,
  [SMALL_STATE(76)] = 2006,
  [SMALL_STATE(77)] = 2015,
  [SMALL_STATE(78)] = 2024,
  [SMALL_STATE(79)] = 2033,
  [SMALL_STATE(80)] = 2042,
  [SMALL_STATE(81)] = 2051,
  [SMALL_STATE(82)] = 2062,
  [SMALL_STATE(83)] = 2073,
  [SMALL_STATE(84)] = 2082,
  [SMALL_STATE(85)] = 2091,
  [SMALL_STATE(86)] = 2102,
  [SMALL_STATE(87)] = 2113,
  [SMALL_STATE(88)] = 2121,
  [SMALL_STATE(89)] = 2129,
  [SMALL_STATE(90)] = 2137,
  [SMALL_STATE(91)] = 2145,
  [SMALL_STATE(92)] = 2153,
  [SMALL_STATE(93)] = 2161,
  [SMALL_STATE(94)] = 2169,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(88),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(54),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(19),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(56),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(5),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(88),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(46),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(54),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 12),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 11),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 19),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_rhs, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 16),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(36),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(17),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(88),
  [119] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(46),
  [122] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(54),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_lhs, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbols, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 15),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 20),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 20),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 4, 0, 25),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbols, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 2, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 23),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 23),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 28),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 28),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_pattern, 2, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_pattern, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_pattern, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_pattern, 3, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [209] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [215] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [218] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [222] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_symbols_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_symbols_repeat1, 2, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [237] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(51),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [250] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [252] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(55),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [257] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 1),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 6),
  [272] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_declaration, 3, 0, 8),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [278] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 2, 0, 13), SHIFT_REPEAT(22),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 2, 0, 13),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 2, 0, 7),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 0),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 1, 0, 2),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 22),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 3),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 1, 0, 5),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 3, 0, 17),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 18),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 3, 0, 21),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block_end, 3, 0, 24),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block_end, 2, 0, 14),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 4),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 2, 0, 9),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 4, 0, 26),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 4, 0, 27),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 10),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [336] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_refal5(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
