#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 82
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 30

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_EQ = 4,
  anon_sym_COMMA = 5,
  anon_sym_COLON = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LT = 9,
  anon_sym_GT = 10,
  anon_sym_DOT = 11,
  sym_ident = 12,
  anon_sym_s = 13,
  anon_sym_e = 14,
  anon_sym_t = 15,
  sym_string = 16,
  sym_number = 17,
  sym_symbols = 18,
  sym_entry_modifier = 19,
  anon_sym_DOLLAREXTERNAL = 20,
  anon_sym_DOLLAREXTERN = 21,
  anon_sym_DOLLAREXTRN = 22,
  sym_comment = 23,
  sym_source_file = 24,
  sym_external_declaration = 25,
  sym_function_name_list = 26,
  sym_function_definition = 27,
  sym_body = 28,
  sym_sentence = 29,
  sym_sentence_eq = 30,
  sym_sentence_block = 31,
  sym_sentence_lhs = 32,
  sym_sentence_rhs = 33,
  sym_sentence_block_end = 34,
  aux_sym__pattern = 35,
  sym_grouped_pattern = 36,
  sym_condition = 37,
  aux_sym__expr = 38,
  sym_function_call = 39,
  sym_grouped_expr = 40,
  sym_variable = 41,
  sym_type = 42,
  sym_external_modifier = 43,
  aux_sym_source_file_repeat1 = 44,
  aux_sym_function_name_list_repeat1 = 45,
  aux_sym_body_repeat1 = 46,
  aux_sym_sentence_eq_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [sym_ident] = "ident",
  [anon_sym_s] = "s",
  [anon_sym_e] = "e",
  [anon_sym_t] = "t",
  [sym_string] = "string",
  [sym_number] = "number",
  [sym_symbols] = "symbols",
  [sym_entry_modifier] = "entry_modifier",
  [anon_sym_DOLLAREXTERNAL] = "$EXTERNAL",
  [anon_sym_DOLLAREXTERN] = "$EXTERN",
  [anon_sym_DOLLAREXTRN] = "$EXTRN",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_external_declaration] = "external_declaration",
  [sym_function_name_list] = "function_name_list",
  [sym_function_definition] = "function_definition",
  [sym_body] = "body",
  [sym_sentence] = "sentence",
  [sym_sentence_eq] = "sentence_eq",
  [sym_sentence_block] = "sentence_block",
  [sym_sentence_lhs] = "sentence_lhs",
  [sym_sentence_rhs] = "sentence_rhs",
  [sym_sentence_block_end] = "sentence_block_end",
  [aux_sym__pattern] = "_pattern",
  [sym_grouped_pattern] = "grouped_pattern",
  [sym_condition] = "condition",
  [aux_sym__expr] = "_expr",
  [sym_function_call] = "function_call",
  [sym_grouped_expr] = "grouped_expr",
  [sym_variable] = "variable",
  [sym_type] = "type",
  [sym_external_modifier] = "external_modifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_name_list_repeat1] = "function_name_list_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_sentence_eq_repeat1] = "sentence_eq_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_ident] = sym_ident,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_t] = anon_sym_t,
  [sym_string] = sym_string,
  [sym_number] = sym_number,
  [sym_symbols] = sym_symbols,
  [sym_entry_modifier] = sym_entry_modifier,
  [anon_sym_DOLLAREXTERNAL] = anon_sym_DOLLAREXTERNAL,
  [anon_sym_DOLLAREXTERN] = anon_sym_DOLLAREXTERN,
  [anon_sym_DOLLAREXTRN] = anon_sym_DOLLAREXTRN,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_external_declaration] = sym_external_declaration,
  [sym_function_name_list] = sym_function_name_list,
  [sym_function_definition] = sym_function_definition,
  [sym_body] = sym_body,
  [sym_sentence] = sym_sentence,
  [sym_sentence_eq] = sym_sentence_eq,
  [sym_sentence_block] = sym_sentence_block,
  [sym_sentence_lhs] = sym_sentence_lhs,
  [sym_sentence_rhs] = sym_sentence_rhs,
  [sym_sentence_block_end] = sym_sentence_block_end,
  [aux_sym__pattern] = aux_sym__pattern,
  [sym_grouped_pattern] = sym_grouped_pattern,
  [sym_condition] = sym_condition,
  [aux_sym__expr] = aux_sym__expr,
  [sym_function_call] = sym_function_call,
  [sym_grouped_expr] = sym_grouped_expr,
  [sym_variable] = sym_variable,
  [sym_type] = sym_type,
  [sym_external_modifier] = sym_external_modifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_name_list_repeat1] = aux_sym_function_name_list_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_sentence_eq_repeat1] = aux_sym_sentence_eq_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_symbols] = {
    .visible = true,
    .named = true,
  },
  [sym_entry_modifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOLLAREXTERNAL] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAREXTERN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAREXTRN] = {
    .visible = true,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_external_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_block] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_lhs] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_rhs] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_block_end] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pattern] = {
    .visible = false,
    .named = false,
  },
  [sym_grouped_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__expr] = {
    .visible = false,
    .named = false,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_external_modifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_name_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_eq_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block = 1,
  field_body = 2,
  field_condition = 3,
  field_entry = 4,
  field_expr = 5,
  field_func_name_list = 6,
  field_lhs = 7,
  field_name = 8,
  field_param = 9,
  field_pattern = 10,
  field_result = 11,
  field_rhs = 12,
  field_sentence_block = 13,
  field_sentence_eq = 14,
  field_type = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block] = "block",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_entry] = "entry",
  [field_expr] = "expr",
  [field_func_name_list] = "func_name_list",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_param] = "param",
  [field_pattern] = "pattern",
  [field_result] = "result",
  [field_rhs] = "rhs",
  [field_sentence_block] = "sentence_block",
  [field_sentence_eq] = "sentence_eq",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 1},
  [7] = {.index = 7, .length = 3},
  [8] = {.index = 10, .length = 1},
  [9] = {.index = 11, .length = 2},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 1},
  [12] = {.index = 15, .length = 1},
  [13] = {.index = 16, .length = 1},
  [14] = {.index = 17, .length = 2},
  [15] = {.index = 19, .length = 1},
  [16] = {.index = 20, .length = 1},
  [17] = {.index = 21, .length = 1},
  [18] = {.index = 22, .length = 2},
  [19] = {.index = 24, .length = 2},
  [20] = {.index = 26, .length = 2},
  [21] = {.index = 28, .length = 2},
  [22] = {.index = 30, .length = 2},
  [23] = {.index = 32, .length = 2},
  [24] = {.index = 34, .length = 1},
  [25] = {.index = 35, .length = 2},
  [26] = {.index = 37, .length = 2},
  [27] = {.index = 39, .length = 3},
  [28] = {.index = 42, .length = 3},
  [29] = {.index = 45, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
    {field_name, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_name, 0, .inherited = true},
  [4] =
    {field_sentence_eq, 0},
  [5] =
    {field_sentence_block, 0},
  [6] =
    {field_condition, 0},
  [7] =
    {field_body, 2},
    {field_entry, 0},
    {field_name, 1},
  [10] =
    {field_func_name_list, 1},
  [11] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [13] =
    {field_rhs, 1},
  [14] =
    {field_block, 1},
  [15] =
    {field_lhs, 0},
  [16] =
    {field_condition, 0, .inherited = true},
  [17] =
    {field_condition, 0, .inherited = true},
    {field_condition, 1, .inherited = true},
  [19] =
    {field_body, 1},
  [20] =
    {field_pattern, 2},
  [21] =
    {field_result, 1},
  [22] =
    {field_lhs, 0},
    {field_rhs, 2},
  [24] =
    {field_block, 2},
    {field_lhs, 0},
  [26] =
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
  [28] =
    {field_name, 2},
    {field_type, 0},
  [30] =
    {field_condition, 0, .inherited = true},
    {field_rhs, 2},
  [32] =
    {field_block, 2},
    {field_condition, 0, .inherited = true},
  [34] =
    {field_name, 1},
  [35] =
    {field_body, 2},
    {field_expr, 0},
  [37] =
    {field_pattern, 3},
    {field_result, 1},
  [39] =
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
    {field_rhs, 3},
  [42] =
    {field_block, 3},
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
  [45] =
    {field_name, 1},
    {field_param, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(21);
      ADVANCE_MAP(
        '"', 1,
        '$', 9,
        '\'', 2,
        '(', 28,
        ')', 29,
        ',', 26,
        '.', 32,
        '/', 6,
        ':', 27,
        ';', 22,
        '<', 30,
        '=', 25,
        '>', 31,
        'e', 36,
        's', 35,
        't', 37,
        '{', 23,
        '}', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(41);
      if (lookahead == '-') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '/') ADVANCE(48);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead != 0) ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == 'E') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'E') ADVANCE(16);
      if (lookahead == 'R') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'L') ADVANCE(44);
      END_STATE();
    case 12:
      if (lookahead == 'N') ADVANCE(17);
      if (lookahead == 'X') ADVANCE(18);
      END_STATE();
    case 13:
      if (lookahead == 'N') ADVANCE(46);
      END_STATE();
    case 14:
      if (lookahead == 'N') ADVANCE(45);
      END_STATE();
    case 15:
      if (lookahead == 'R') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'R') ADVANCE(14);
      END_STATE();
    case 17:
      if (lookahead == 'T') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 'T') ADVANCE(10);
      END_STATE();
    case 19:
      if (lookahead == 'Y') ADVANCE(43);
      END_STATE();
    case 20:
      if (eof) ADVANCE(21);
      if (lookahead == '$') ADVANCE(9);
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == ';') ADVANCE(22);
      if (lookahead == '}') ADVANCE(24);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_s);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_e);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_t);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(34);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_symbols);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_symbols);
      if (lookahead == '\'') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_symbols);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_entry_modifier);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTERNAL);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTERN);
      if (lookahead == 'A') ADVANCE(11);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOLLAREXTRN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 20},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 20},
  [41] = {.lex_state = 20},
  [42] = {.lex_state = 20},
  [43] = {.lex_state = 20},
  [44] = {.lex_state = 20},
  [45] = {.lex_state = 20},
  [46] = {.lex_state = 20},
  [47] = {.lex_state = 20},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 20},
  [53] = {.lex_state = 20},
  [54] = {.lex_state = 20},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 20},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 20},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 20},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 20},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 20},
  [81] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_symbols] = ACTIONS(1),
    [sym_entry_modifier] = ACTIONS(1),
    [anon_sym_DOLLAREXTERNAL] = ACTIONS(1),
    [anon_sym_DOLLAREXTERN] = ACTIONS(1),
    [anon_sym_DOLLAREXTRN] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(81),
    [sym_external_declaration] = STATE(40),
    [sym_function_definition] = STATE(40),
    [sym_external_modifier] = STATE(52),
    [aux_sym_source_file_repeat1] = STATE(40),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [sym_entry_modifier] = ACTIONS(9),
    [anon_sym_DOLLAREXTERNAL] = ACTIONS(11),
    [anon_sym_DOLLAREXTERN] = ACTIONS(13),
    [anon_sym_DOLLAREXTRN] = ACTIONS(11),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_RBRACE,
    ACTIONS(17), 1,
      anon_sym_EQ,
    ACTIONS(20), 1,
      anon_sym_COMMA,
    ACTIONS(23), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 1,
      sym_string,
    STATE(2), 1,
      aux_sym_body_repeat1,
    STATE(48), 1,
      sym_sentence_lhs,
    STATE(51), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(56), 1,
      sym_condition,
    STATE(63), 1,
      sym_sentence_eq,
    STATE(71), 1,
      sym_sentence_block,
    STATE(74), 1,
      sym_type,
    STATE(77), 1,
      sym_sentence,
    ACTIONS(26), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(29), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(27), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [58] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    ACTIONS(37), 1,
      anon_sym_EQ,
    ACTIONS(39), 1,
      anon_sym_COMMA,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      sym_string,
    STATE(2), 1,
      aux_sym_body_repeat1,
    STATE(48), 1,
      sym_sentence_lhs,
    STATE(51), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(56), 1,
      sym_condition,
    STATE(59), 1,
      sym_sentence,
    STATE(63), 1,
      sym_sentence_eq,
    STATE(71), 1,
      sym_sentence_block,
    STATE(74), 1,
      sym_type,
    ACTIONS(43), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(27), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [116] = 17,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(37), 1,
      anon_sym_EQ,
    ACTIONS(39), 1,
      anon_sym_COMMA,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(47), 1,
      sym_string,
    ACTIONS(49), 1,
      anon_sym_RBRACE,
    STATE(3), 1,
      aux_sym_body_repeat1,
    STATE(48), 1,
      sym_sentence_lhs,
    STATE(51), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(56), 1,
      sym_condition,
    STATE(58), 1,
      sym_sentence,
    STATE(63), 1,
      sym_sentence_eq,
    STATE(71), 1,
      sym_sentence_block,
    STATE(74), 1,
      sym_type,
    ACTIONS(43), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(27), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [174] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_LT,
    ACTIONS(65), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(59), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(62), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
    ACTIONS(51), 5,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_GT,
  [213] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(76), 1,
      sym_string,
    STATE(62), 1,
      sym_sentence_rhs,
    STATE(74), 1,
      sym_type,
    ACTIONS(68), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(74), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(13), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [252] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(76), 1,
      sym_string,
    STATE(67), 1,
      sym_sentence_rhs,
    STATE(74), 1,
      sym_type,
    ACTIONS(78), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(74), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(13), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [291] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(76), 1,
      sym_string,
    STATE(61), 1,
      sym_sentence_rhs,
    STATE(74), 1,
      sym_type,
    ACTIONS(80), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(74), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(13), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [330] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(76), 1,
      sym_string,
    STATE(55), 1,
      sym_sentence_rhs,
    STATE(74), 1,
      sym_type,
    ACTIONS(82), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(74), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(13), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [369] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(88), 1,
      sym_string,
    STATE(64), 1,
      sym_sentence_block_end,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(86), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(21), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [407] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(88), 1,
      sym_string,
    STATE(60), 1,
      sym_sentence_block_end,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(86), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(21), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [445] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(88), 1,
      sym_string,
    STATE(66), 1,
      sym_sentence_block_end,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(86), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(21), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [483] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(94), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(90), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(92), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(5), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [519] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(84), 1,
      anon_sym_COLON,
    ACTIONS(88), 1,
      sym_string,
    STATE(72), 1,
      sym_sentence_block_end,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(86), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(21), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [557] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(96), 1,
      anon_sym_LBRACE,
    ACTIONS(102), 1,
      sym_string,
    STATE(69), 1,
      sym_body,
    STATE(74), 1,
      sym_type,
    ACTIONS(98), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(100), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(30), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [595] = 10,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(96), 1,
      anon_sym_LBRACE,
    ACTIONS(108), 1,
      sym_string,
    STATE(57), 1,
      sym_body,
    STATE(74), 1,
      sym_type,
    ACTIONS(104), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(106), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(31), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [633] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(112), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(110), 10,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [657] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(114), 1,
      anon_sym_RPAREN,
    ACTIONS(118), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(116), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(20), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [692] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(120), 1,
      anon_sym_GT,
    ACTIONS(124), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(122), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(23), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [727] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(94), 1,
      sym_string,
    ACTIONS(126), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(92), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(5), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [762] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(94), 1,
      sym_string,
    ACTIONS(128), 1,
      anon_sym_COLON,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(92), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(5), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [797] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(132), 1,
      anon_sym_LPAREN,
    ACTIONS(141), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(130), 3,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    ACTIONS(135), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    ACTIONS(138), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(22), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [830] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(94), 1,
      sym_string,
    ACTIONS(144), 1,
      anon_sym_GT,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(92), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(5), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [865] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(94), 1,
      sym_string,
    ACTIONS(146), 1,
      anon_sym_COLON,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(92), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(5), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [900] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(70), 1,
      anon_sym_LPAREN,
    ACTIONS(72), 1,
      anon_sym_LT,
    ACTIONS(148), 1,
      anon_sym_COLON,
    ACTIONS(152), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(150), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(24), 4,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
  [935] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(156), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(154), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [957] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(158), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(160), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(22), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [989] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(164), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [1011] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(168), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [1033] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(172), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(160), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(22), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [1065] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(174), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(160), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(22), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [1097] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(108), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(104), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(106), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(31), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [1129] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
    ACTIONS(176), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      sym_string,
  [1151] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(102), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(98), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(100), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(30), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [1183] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(180), 1,
      anon_sym_RPAREN,
    ACTIONS(184), 1,
      sym_string,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(182), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(36), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [1214] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(41), 1,
      anon_sym_LPAREN,
    ACTIONS(162), 1,
      sym_string,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    STATE(74), 1,
      sym_type,
    ACTIONS(45), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(160), 3,
      sym_ident,
      sym_number,
      sym_symbols,
    STATE(22), 3,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
  [1245] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(15), 5,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      sym_string,
    ACTIONS(188), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
  [1264] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 5,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(192), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
  [1283] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(194), 5,
      anon_sym_EQ,
      anon_sym_COMMA,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_string,
    ACTIONS(196), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      sym_symbols,
  [1302] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(9), 1,
      sym_entry_modifier,
    ACTIONS(13), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(198), 1,
      ts_builtin_sym_end,
    STATE(52), 1,
      sym_external_modifier,
    ACTIONS(11), 2,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
    STATE(41), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1330] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(200), 1,
      ts_builtin_sym_end,
    ACTIONS(202), 1,
      sym_ident,
    ACTIONS(205), 1,
      sym_entry_modifier,
    ACTIONS(211), 1,
      anon_sym_DOLLAREXTERN,
    STATE(52), 1,
      sym_external_modifier,
    ACTIONS(208), 2,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
    STATE(41), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1358] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(216), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(214), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1374] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(218), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1390] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(222), 7,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1406] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(226), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1420] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(230), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1434] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_DOLLAREXTERN,
    ACTIONS(234), 5,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      anon_sym_DOLLAREXTERNAL,
      anon_sym_DOLLAREXTRN,
  [1448] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_EQ,
    ACTIONS(240), 1,
      anon_sym_COMMA,
    STATE(50), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(56), 1,
      sym_condition,
  [1464] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_EQ,
    ACTIONS(244), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(56), 1,
      sym_condition,
  [1480] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(247), 1,
      anon_sym_EQ,
    ACTIONS(249), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(56), 1,
      sym_condition,
  [1496] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(251), 1,
      anon_sym_EQ,
    ACTIONS(253), 1,
      anon_sym_COMMA,
    STATE(49), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(56), 1,
      sym_condition,
  [1512] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_ident,
    STATE(54), 1,
      aux_sym_function_name_list_repeat1,
    STATE(79), 1,
      sym_function_name_list,
  [1525] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(257), 1,
      anon_sym_SEMI,
    ACTIONS(259), 1,
      sym_ident,
    STATE(53), 1,
      aux_sym_function_name_list_repeat1,
  [1538] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(255), 1,
      sym_ident,
    ACTIONS(262), 1,
      anon_sym_SEMI,
    STATE(53), 1,
      aux_sym_function_name_list_repeat1,
  [1551] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(264), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1559] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 2,
      anon_sym_EQ,
      anon_sym_COMMA,
  [1567] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1575] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    ACTIONS(270), 1,
      anon_sym_SEMI,
  [1585] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_SEMI,
    ACTIONS(272), 1,
      anon_sym_RBRACE,
  [1595] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(274), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1603] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(276), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1611] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(278), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1619] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1627] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(282), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1635] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(284), 2,
      anon_sym_SEMI,
      sym_ident,
  [1643] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(286), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1651] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(288), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1659] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_LBRACE,
    STATE(46), 1,
      sym_body,
  [1669] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(290), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1677] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(96), 1,
      anon_sym_LBRACE,
    STATE(47), 1,
      sym_body,
  [1687] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(292), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1695] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(294), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [1703] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(296), 1,
      sym_ident,
  [1710] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(298), 1,
      anon_sym_DOT,
  [1717] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(300), 1,
      anon_sym_DOT,
  [1724] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(302), 1,
      sym_ident,
  [1731] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      anon_sym_SEMI,
  [1738] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(304), 1,
      sym_ident,
  [1745] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(306), 1,
      anon_sym_SEMI,
  [1752] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(308), 1,
      sym_ident,
  [1759] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(310), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 58,
  [SMALL_STATE(4)] = 116,
  [SMALL_STATE(5)] = 174,
  [SMALL_STATE(6)] = 213,
  [SMALL_STATE(7)] = 252,
  [SMALL_STATE(8)] = 291,
  [SMALL_STATE(9)] = 330,
  [SMALL_STATE(10)] = 369,
  [SMALL_STATE(11)] = 407,
  [SMALL_STATE(12)] = 445,
  [SMALL_STATE(13)] = 483,
  [SMALL_STATE(14)] = 519,
  [SMALL_STATE(15)] = 557,
  [SMALL_STATE(16)] = 595,
  [SMALL_STATE(17)] = 633,
  [SMALL_STATE(18)] = 657,
  [SMALL_STATE(19)] = 692,
  [SMALL_STATE(20)] = 727,
  [SMALL_STATE(21)] = 762,
  [SMALL_STATE(22)] = 797,
  [SMALL_STATE(23)] = 830,
  [SMALL_STATE(24)] = 865,
  [SMALL_STATE(25)] = 900,
  [SMALL_STATE(26)] = 935,
  [SMALL_STATE(27)] = 957,
  [SMALL_STATE(28)] = 989,
  [SMALL_STATE(29)] = 1011,
  [SMALL_STATE(30)] = 1033,
  [SMALL_STATE(31)] = 1065,
  [SMALL_STATE(32)] = 1097,
  [SMALL_STATE(33)] = 1129,
  [SMALL_STATE(34)] = 1151,
  [SMALL_STATE(35)] = 1183,
  [SMALL_STATE(36)] = 1214,
  [SMALL_STATE(37)] = 1245,
  [SMALL_STATE(38)] = 1264,
  [SMALL_STATE(39)] = 1283,
  [SMALL_STATE(40)] = 1302,
  [SMALL_STATE(41)] = 1330,
  [SMALL_STATE(42)] = 1358,
  [SMALL_STATE(43)] = 1374,
  [SMALL_STATE(44)] = 1390,
  [SMALL_STATE(45)] = 1406,
  [SMALL_STATE(46)] = 1420,
  [SMALL_STATE(47)] = 1434,
  [SMALL_STATE(48)] = 1448,
  [SMALL_STATE(49)] = 1464,
  [SMALL_STATE(50)] = 1480,
  [SMALL_STATE(51)] = 1496,
  [SMALL_STATE(52)] = 1512,
  [SMALL_STATE(53)] = 1525,
  [SMALL_STATE(54)] = 1538,
  [SMALL_STATE(55)] = 1551,
  [SMALL_STATE(56)] = 1559,
  [SMALL_STATE(57)] = 1567,
  [SMALL_STATE(58)] = 1575,
  [SMALL_STATE(59)] = 1585,
  [SMALL_STATE(60)] = 1595,
  [SMALL_STATE(61)] = 1603,
  [SMALL_STATE(62)] = 1611,
  [SMALL_STATE(63)] = 1619,
  [SMALL_STATE(64)] = 1627,
  [SMALL_STATE(65)] = 1635,
  [SMALL_STATE(66)] = 1643,
  [SMALL_STATE(67)] = 1651,
  [SMALL_STATE(68)] = 1659,
  [SMALL_STATE(69)] = 1669,
  [SMALL_STATE(70)] = 1677,
  [SMALL_STATE(71)] = 1687,
  [SMALL_STATE(72)] = 1695,
  [SMALL_STATE(73)] = 1703,
  [SMALL_STATE(74)] = 1710,
  [SMALL_STATE(75)] = 1717,
  [SMALL_STATE(76)] = 1724,
  [SMALL_STATE(77)] = 1731,
  [SMALL_STATE(78)] = 1738,
  [SMALL_STATE(79)] = 1745,
  [SMALL_STATE(80)] = 1752,
  [SMALL_STATE(81)] = 1759,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(75),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(18),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(78),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(5),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(75),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(5),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 13),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [74] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 12),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 20),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_rhs, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 17),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 21),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 21),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(35),
  [135] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(22),
  [138] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(75),
  [141] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(22),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 2, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_lhs, 1, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 24),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 24),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 4, 0, 26),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 16),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 29),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 29),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [182] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_pattern, 2, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_pattern, 2, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_pattern, 3, 0, 0),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_pattern, 3, 0, 0),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [211] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(80),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 3, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 4, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_declaration, 3, 0, 8),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_external_declaration, 3, 0, 8),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 7),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 3, 0, 7),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 1),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 2, 0, 1),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 2, 0, 14),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 2, 0, 14), SHIFT_REPEAT(25),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 9),
  [259] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 9), SHIFT_REPEAT(65),
  [262] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 1, 0, 3),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 4, 0, 27),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 1, 0, 6),
  [268] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block_end, 2, 0, 15),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 3, 0, 19),
  [276] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 18),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 22),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 4),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 3, 0, 23),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 1, 0, 2),
  [286] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 2, 0, 11),
  [288] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 10),
  [290] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block_end, 3, 0, 25),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 5),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 4, 0, 28),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_modifier, 1, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_refal5(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
