#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 99
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 60
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 15
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 29

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  anon_sym_COMMA = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_EQ = 5,
  anon_sym_COLON = 6,
  anon_sym_LPAREN = 7,
  anon_sym_RPAREN = 8,
  anon_sym_LT = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_STAR = 12,
  anon_sym_SLASH = 13,
  anon_sym_GT = 14,
  anon_sym_DOT = 15,
  sym_ident = 16,
  anon_sym_s = 17,
  anon_sym_e = 18,
  anon_sym_t = 19,
  aux_sym_string_token1 = 20,
  anon_sym_BSLASH_BSLASH = 21,
  anon_sym_BSLASH_DQUOTE = 22,
  aux_sym_string_token2 = 23,
  sym_number = 24,
  aux_sym_symbols_token1 = 25,
  anon_sym_BSLASH_SQUOTE = 26,
  aux_sym_symbols_token2 = 27,
  sym_entry_modifier = 28,
  sym_external_modifier = 29,
  sym_comment = 30,
  sym_line_comment = 31,
  sym_source_file = 32,
  sym_external_declaration = 33,
  sym_function_name_list = 34,
  sym_function_definition = 35,
  sym_body = 36,
  sym_sentence = 37,
  sym_sentence_eq = 38,
  sym_sentence_block = 39,
  sym_sentence_lhs = 40,
  sym_sentence_rhs = 41,
  sym_sentence_block_end = 42,
  aux_sym__pattern = 43,
  sym_grouped_pattern = 44,
  sym_condition = 45,
  aux_sym__expr = 46,
  sym_function_call = 47,
  sym_grouped_expr = 48,
  sym_variable = 49,
  sym_type = 50,
  sym_string = 51,
  sym_symbols = 52,
  aux_sym_source_file_repeat1 = 53,
  aux_sym_function_name_list_repeat1 = 54,
  aux_sym_body_repeat1 = 55,
  aux_sym_sentence_eq_repeat1 = 56,
  aux_sym_string_repeat1 = 57,
  aux_sym_string_repeat2 = 58,
  aux_sym_symbols_repeat1 = 59,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_GT] = ">",
  [anon_sym_DOT] = ".",
  [sym_ident] = "ident",
  [anon_sym_s] = "s",
  [anon_sym_e] = "e",
  [anon_sym_t] = "t",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_BSLASH_BSLASH] = "\\\\",
  [anon_sym_BSLASH_DQUOTE] = "\\\"",
  [aux_sym_string_token2] = "string_token2",
  [sym_number] = "number",
  [aux_sym_symbols_token1] = "symbols_token1",
  [anon_sym_BSLASH_SQUOTE] = "\\'",
  [aux_sym_symbols_token2] = "symbols_token2",
  [sym_entry_modifier] = "entry_modifier",
  [sym_external_modifier] = "external_modifier",
  [sym_comment] = "comment",
  [sym_line_comment] = "line_comment",
  [sym_source_file] = "source_file",
  [sym_external_declaration] = "external_declaration",
  [sym_function_name_list] = "function_name_list",
  [sym_function_definition] = "function_definition",
  [sym_body] = "body",
  [sym_sentence] = "sentence",
  [sym_sentence_eq] = "sentence_eq",
  [sym_sentence_block] = "sentence_block",
  [sym_sentence_lhs] = "sentence_lhs",
  [sym_sentence_rhs] = "sentence_rhs",
  [sym_sentence_block_end] = "sentence_block_end",
  [aux_sym__pattern] = "_pattern",
  [sym_grouped_pattern] = "grouped_pattern",
  [sym_condition] = "condition",
  [aux_sym__expr] = "_expr",
  [sym_function_call] = "function_call",
  [sym_grouped_expr] = "grouped_expr",
  [sym_variable] = "variable",
  [sym_type] = "type",
  [sym_string] = "string",
  [sym_symbols] = "symbols",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_name_list_repeat1] = "function_name_list_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_sentence_eq_repeat1] = "sentence_eq_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym_symbols_repeat1] = "symbols_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_ident] = sym_ident,
  [anon_sym_s] = anon_sym_s,
  [anon_sym_e] = anon_sym_e,
  [anon_sym_t] = anon_sym_t,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_BSLASH_BSLASH] = anon_sym_BSLASH_BSLASH,
  [anon_sym_BSLASH_DQUOTE] = anon_sym_BSLASH_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_number] = sym_number,
  [aux_sym_symbols_token1] = aux_sym_symbols_token1,
  [anon_sym_BSLASH_SQUOTE] = anon_sym_BSLASH_SQUOTE,
  [aux_sym_symbols_token2] = aux_sym_symbols_token2,
  [sym_entry_modifier] = sym_entry_modifier,
  [sym_external_modifier] = sym_external_modifier,
  [sym_comment] = sym_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_source_file] = sym_source_file,
  [sym_external_declaration] = sym_external_declaration,
  [sym_function_name_list] = sym_function_name_list,
  [sym_function_definition] = sym_function_definition,
  [sym_body] = sym_body,
  [sym_sentence] = sym_sentence,
  [sym_sentence_eq] = sym_sentence_eq,
  [sym_sentence_block] = sym_sentence_block,
  [sym_sentence_lhs] = sym_sentence_lhs,
  [sym_sentence_rhs] = sym_sentence_rhs,
  [sym_sentence_block_end] = sym_sentence_block_end,
  [aux_sym__pattern] = aux_sym__pattern,
  [sym_grouped_pattern] = sym_grouped_pattern,
  [sym_condition] = sym_condition,
  [aux_sym__expr] = aux_sym__expr,
  [sym_function_call] = sym_function_call,
  [sym_grouped_expr] = sym_grouped_expr,
  [sym_variable] = sym_variable,
  [sym_type] = sym_type,
  [sym_string] = sym_string,
  [sym_symbols] = sym_symbols,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_name_list_repeat1] = aux_sym_function_name_list_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_sentence_eq_repeat1] = aux_sym_sentence_eq_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym_symbols_repeat1] = aux_sym_symbols_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_s] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_e] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_t] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_symbols_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BSLASH_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_symbols_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_entry_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_external_modifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_external_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_function_name_list] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_eq] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_block] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_lhs] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_rhs] = {
    .visible = true,
    .named = true,
  },
  [sym_sentence_block_end] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__pattern] = {
    .visible = false,
    .named = false,
  },
  [sym_grouped_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__expr] = {
    .visible = false,
    .named = false,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_grouped_expr] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_symbols] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_name_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_sentence_eq_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_symbols_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_block = 1,
  field_body = 2,
  field_condition = 3,
  field_entry = 4,
  field_expr = 5,
  field_func_name_list = 6,
  field_lhs = 7,
  field_name = 8,
  field_param = 9,
  field_pattern = 10,
  field_result = 11,
  field_rhs = 12,
  field_sentence_block = 13,
  field_sentence_eq = 14,
  field_type = 15,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_block] = "block",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_entry] = "entry",
  [field_expr] = "expr",
  [field_func_name_list] = "func_name_list",
  [field_lhs] = "lhs",
  [field_name] = "name",
  [field_param] = "param",
  [field_pattern] = "pattern",
  [field_result] = "result",
  [field_rhs] = "rhs",
  [field_sentence_block] = "sentence_block",
  [field_sentence_eq] = "sentence_eq",
  [field_type] = "type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 1},
  [5] = {.index = 5, .length = 1},
  [6] = {.index = 6, .length = 3},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 1},
  [9] = {.index = 12, .length = 1},
  [10] = {.index = 13, .length = 1},
  [11] = {.index = 14, .length = 1},
  [12] = {.index = 15, .length = 1},
  [13] = {.index = 16, .length = 2},
  [14] = {.index = 18, .length = 1},
  [15] = {.index = 19, .length = 1},
  [16] = {.index = 20, .length = 1},
  [17] = {.index = 21, .length = 2},
  [18] = {.index = 23, .length = 2},
  [19] = {.index = 25, .length = 2},
  [20] = {.index = 27, .length = 2},
  [21] = {.index = 29, .length = 2},
  [22] = {.index = 31, .length = 2},
  [23] = {.index = 33, .length = 1},
  [24] = {.index = 34, .length = 2},
  [25] = {.index = 36, .length = 2},
  [26] = {.index = 38, .length = 3},
  [27] = {.index = 41, .length = 3},
  [28] = {.index = 44, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 1},
    {field_name, 0},
  [2] =
    {field_name, 0},
  [3] =
    {field_sentence_eq, 0},
  [4] =
    {field_sentence_block, 0},
  [5] =
    {field_condition, 0},
  [6] =
    {field_body, 2},
    {field_entry, 0},
    {field_name, 1},
  [9] =
    {field_name, 0},
    {field_name, 1},
  [11] =
    {field_func_name_list, 1},
  [12] =
    {field_block, 1},
  [13] =
    {field_rhs, 1},
  [14] =
    {field_lhs, 0},
  [15] =
    {field_condition, 0, .inherited = true},
  [16] =
    {field_condition, 0, .inherited = true},
    {field_condition, 1, .inherited = true},
  [18] =
    {field_body, 1},
  [19] =
    {field_pattern, 2},
  [20] =
    {field_result, 1},
  [21] =
    {field_block, 2},
    {field_lhs, 0},
  [23] =
    {field_lhs, 0},
    {field_rhs, 2},
  [25] =
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
  [27] =
    {field_name, 2},
    {field_type, 0},
  [29] =
    {field_block, 2},
    {field_condition, 0, .inherited = true},
  [31] =
    {field_condition, 0, .inherited = true},
    {field_rhs, 2},
  [33] =
    {field_name, 1},
  [34] =
    {field_body, 2},
    {field_expr, 0},
  [36] =
    {field_pattern, 3},
    {field_result, 1},
  [38] =
    {field_block, 3},
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
  [41] =
    {field_condition, 1, .inherited = true},
    {field_lhs, 0},
    {field_rhs, 3},
  [44] =
    {field_name, 1},
    {field_param, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 59,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '"', 45,
        '$', 11,
        '\'', 53,
        '(', 31,
        ')', 32,
        '*', 36,
        '+', 34,
        ',', 26,
        '-', 35,
        '.', 39,
        '/', 37,
        ':', 30,
        ';', 25,
        '<', 33,
        '=', 29,
        '>', 38,
        '\\', 4,
        'e', 43,
        's', 42,
        't', 44,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead == '\\') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(2);
      if (lookahead == '\'') ADVANCE(52);
      if (lookahead == '*') ADVANCE(55);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(56);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '"', 45,
        '\'', 53,
        '(', 31,
        ')', 32,
        '*', 62,
        ',', 26,
        '/', 8,
        ':', 30,
        ';', 25,
        '<', 33,
        '=', 29,
        '>', 38,
        'e', 43,
        's', 42,
        't', 44,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(46);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(22);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(36);
      if (lookahead == '+') ADVANCE(34);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead == '/') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 8:
      if (lookahead == '*') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == '*') ADVANCE(10);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '/') ADVANCE(61);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 'E') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'E') ADVANCE(18);
      if (lookahead == 'R') ADVANCE(15);
      END_STATE();
    case 13:
      if (lookahead == 'L') ADVANCE(59);
      END_STATE();
    case 14:
      if (lookahead == 'N') ADVANCE(19);
      if (lookahead == 'X') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'N') ADVANCE(59);
      END_STATE();
    case 16:
      if (lookahead == 'N') ADVANCE(60);
      END_STATE();
    case 17:
      if (lookahead == 'R') ADVANCE(21);
      END_STATE();
    case 18:
      if (lookahead == 'R') ADVANCE(16);
      END_STATE();
    case 19:
      if (lookahead == 'T') ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == 'T') ADVANCE(12);
      END_STATE();
    case 21:
      if (lookahead == 'Y') ADVANCE(58);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      ADVANCE_MAP(
        '$', 11,
        '*', 62,
        ',', 26,
        '.', 39,
        '/', 8,
        ';', 25,
        '=', 29,
        '{', 27,
        '}', 28,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_ident);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_s);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_e);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_t);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_string_token1);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_BSLASH_BSLASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_BSLASH_DQUOTE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_string_token2);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '"') ADVANCE(47);
      if (lookahead == '\\') ADVANCE(46);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(48);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '"') ADVANCE(48);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_symbols_token1);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_symbols_token1);
      if (lookahead == '\'') ADVANCE(5);
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_BSLASH_SQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_symbols_token2);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_symbols_token2);
      if (lookahead == '\'') ADVANCE(54);
      if (lookahead == '\\') ADVANCE(46);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_symbols_token2);
      if (lookahead == '*') ADVANCE(55);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(56);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '\'') ADVANCE(55);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entry_modifier);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_external_modifier);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_external_modifier);
      if (lookahead == 'A') ADVANCE(13);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 23},
  [47] = {.lex_state = 23},
  [48] = {.lex_state = 23},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 23},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 23},
  [57] = {.lex_state = 23},
  [58] = {.lex_state = 23},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 7},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 23},
  [63] = {.lex_state = 23},
  [64] = {.lex_state = 23},
  [65] = {.lex_state = 23},
  [66] = {.lex_state = 23},
  [67] = {.lex_state = 23},
  [68] = {.lex_state = 23},
  [69] = {.lex_state = 23},
  [70] = {.lex_state = 23},
  [71] = {.lex_state = 23},
  [72] = {.lex_state = 23},
  [73] = {.lex_state = 23},
  [74] = {.lex_state = 23},
  [75] = {.lex_state = 23},
  [76] = {.lex_state = 23},
  [77] = {.lex_state = 23},
  [78] = {.lex_state = 23},
  [79] = {.lex_state = 23},
  [80] = {.lex_state = 23},
  [81] = {.lex_state = 23},
  [82] = {.lex_state = 23},
  [83] = {.lex_state = 23},
  [84] = {.lex_state = 23},
  [85] = {.lex_state = 23},
  [86] = {.lex_state = 23},
  [87] = {.lex_state = 23},
  [88] = {.lex_state = 23},
  [89] = {.lex_state = 23},
  [90] = {.lex_state = 23},
  [91] = {.lex_state = 23},
  [92] = {.lex_state = 23},
  [93] = {.lex_state = 23},
  [94] = {.lex_state = 23},
  [95] = {.lex_state = 23},
  [96] = {.lex_state = 23},
  [97] = {.lex_state = 23},
  [98] = {.lex_state = 23},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [anon_sym_s] = ACTIONS(1),
    [anon_sym_e] = ACTIONS(1),
    [anon_sym_t] = ACTIONS(1),
    [aux_sym_string_token1] = ACTIONS(1),
    [anon_sym_BSLASH_BSLASH] = ACTIONS(1),
    [anon_sym_BSLASH_DQUOTE] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [aux_sym_symbols_token1] = ACTIONS(1),
    [anon_sym_BSLASH_SQUOTE] = ACTIONS(1),
    [sym_entry_modifier] = ACTIONS(1),
    [sym_external_modifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_line_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(98),
    [sym_external_declaration] = STATE(47),
    [sym_function_definition] = STATE(47),
    [aux_sym_source_file_repeat1] = STATE(47),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_ident] = ACTIONS(7),
    [sym_entry_modifier] = ACTIONS(9),
    [sym_external_modifier] = ACTIONS(11),
    [sym_comment] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(17), 1,
      anon_sym_EQ,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    STATE(3), 1,
      aux_sym_body_repeat1,
    STATE(66), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(68), 1,
      sym_sentence_lhs,
    STATE(73), 1,
      sym_sentence_eq,
    STATE(83), 1,
      sym_sentence,
    STATE(84), 1,
      sym_sentence_block,
    STATE(89), 1,
      sym_condition,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(21), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(25), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [60] = 17,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(17), 1,
      anon_sym_EQ,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    STATE(4), 1,
      aux_sym_body_repeat1,
    STATE(66), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(68), 1,
      sym_sentence_lhs,
    STATE(73), 1,
      sym_sentence_eq,
    STATE(84), 1,
      sym_sentence_block,
    STATE(89), 1,
      sym_condition,
    STATE(90), 1,
      sym_sentence,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(21), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(25), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [120] = 17,
    ACTIONS(29), 1,
      anon_sym_COMMA,
    ACTIONS(32), 1,
      anon_sym_EQ,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(44), 1,
      aux_sym_string_token1,
    ACTIONS(47), 1,
      aux_sym_symbols_token1,
    STATE(4), 1,
      aux_sym_body_repeat1,
    STATE(66), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(68), 1,
      sym_sentence_lhs,
    STATE(73), 1,
      sym_sentence_eq,
    STATE(84), 1,
      sym_sentence_block,
    STATE(89), 1,
      sym_condition,
    STATE(91), 1,
      sym_sentence,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(38), 2,
      sym_ident,
      sym_number,
    ACTIONS(41), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(25), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [180] = 10,
    ACTIONS(52), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LT,
    ACTIONS(64), 1,
      aux_sym_string_token1,
    ACTIONS(67), 1,
      aux_sym_symbols_token1,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(58), 2,
      sym_ident,
      sym_number,
    ACTIONS(61), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    ACTIONS(50), 5,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_RPAREN,
      anon_sym_GT,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [224] = 11,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    STATE(76), 1,
      sym_sentence_rhs,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(70), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(76), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [268] = 11,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    STATE(80), 1,
      sym_sentence_rhs,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(76), 2,
      sym_ident,
      sym_number,
    ACTIONS(78), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [312] = 11,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    STATE(81), 1,
      sym_sentence_rhs,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(76), 2,
      sym_ident,
      sym_number,
    ACTIONS(80), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [356] = 11,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    STATE(72), 1,
      sym_sentence_rhs,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(76), 2,
      sym_ident,
      sym_number,
    ACTIONS(82), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(12), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [400] = 11,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(84), 1,
      anon_sym_COLON,
    STATE(75), 1,
      sym_sentence_block_end,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(19), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [443] = 11,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(84), 1,
      anon_sym_COLON,
    STATE(77), 1,
      sym_sentence_block_end,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(19), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [486] = 10,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(88), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
    ACTIONS(90), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [527] = 11,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    STATE(85), 1,
      sym_body,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(92), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(96), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(27), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [570] = 11,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(84), 1,
      anon_sym_COLON,
    STATE(82), 1,
      sym_sentence_block_end,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(19), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [613] = 11,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(84), 1,
      anon_sym_COLON,
    STATE(88), 1,
      sym_sentence_block_end,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(86), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(19), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [656] = 11,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    STATE(86), 1,
      sym_body,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(98), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(100), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(31), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [699] = 9,
    ACTIONS(104), 1,
      anon_sym_LPAREN,
    ACTIONS(113), 1,
      aux_sym_string_token1,
    ACTIONS(116), 1,
      aux_sym_symbols_token1,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(107), 2,
      sym_ident,
      sym_number,
    ACTIONS(102), 3,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_RPAREN,
    ACTIONS(110), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [737] = 10,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(119), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(121), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(23), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [777] = 10,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(123), 1,
      anon_sym_COLON,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(90), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [817] = 10,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(125), 1,
      anon_sym_GT,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(127), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(24), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [857] = 10,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(129), 1,
      anon_sym_COLON,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(131), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(22), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [897] = 10,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(133), 1,
      anon_sym_COLON,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(90), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [937] = 10,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(135), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(90), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [977] = 10,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(72), 1,
      anon_sym_LPAREN,
    ACTIONS(74), 1,
      anon_sym_LT,
    ACTIONS(137), 1,
      anon_sym_GT,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(90), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(5), 6,
      aux_sym__expr,
      sym_function_call,
      sym_grouped_expr,
      sym_variable,
      sym_string,
      sym_symbols,
  [1017] = 9,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(139), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(141), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1054] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(145), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(143), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1079] = 9,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(141), 2,
      sym_ident,
      sym_number,
    ACTIONS(147), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1116] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(151), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(149), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1141] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(155), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(153), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1166] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(159), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(157), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1191] = 9,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(141), 2,
      sym_ident,
      sym_number,
    ACTIONS(161), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1228] = 9,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(92), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(96), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(27), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1265] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(165), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(163), 10,
      anon_sym_SEMI,
      anon_sym_COMMA,
      anon_sym_RBRACE,
      anon_sym_EQ,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1290] = 9,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(98), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
    ACTIONS(100), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(31), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1327] = 9,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(167), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(141), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(17), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1363] = 9,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(25), 1,
      aux_sym_string_token1,
    ACTIONS(27), 1,
      aux_sym_symbols_token1,
    ACTIONS(169), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym_type,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(171), 2,
      sym_ident,
      sym_number,
    ACTIONS(23), 3,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
    STATE(35), 5,
      aux_sym__pattern,
      sym_grouped_pattern,
      sym_variable,
      sym_string,
      sym_symbols,
  [1399] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(175), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(173), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1422] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(179), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(177), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1445] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(183), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(181), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1468] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(187), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
    ACTIONS(185), 8,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LT,
      anon_sym_GT,
      aux_sym_string_token1,
  [1491] = 4,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(189), 4,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      aux_sym_string_token1,
    ACTIONS(193), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
  [1513] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(195), 5,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_string_token1,
    ACTIONS(197), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
  [1533] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(199), 5,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      aux_sym_string_token1,
    ACTIONS(201), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
  [1553] = 4,
    ACTIONS(203), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(189), 4,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      aux_sym_string_token1,
    ACTIONS(193), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
  [1575] = 3,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(189), 4,
      anon_sym_COMMA,
      anon_sym_EQ,
      anon_sym_LPAREN,
      aux_sym_string_token1,
    ACTIONS(193), 6,
      sym_ident,
      anon_sym_s,
      anon_sym_e,
      anon_sym_t,
      sym_number,
      aux_sym_symbols_token1,
  [1594] = 6,
    ACTIONS(205), 1,
      ts_builtin_sym_end,
    ACTIONS(207), 1,
      sym_ident,
    ACTIONS(210), 1,
      sym_entry_modifier,
    ACTIONS(213), 1,
      sym_external_modifier,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    STATE(46), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1616] = 6,
    ACTIONS(7), 1,
      sym_ident,
    ACTIONS(9), 1,
      sym_entry_modifier,
    ACTIONS(11), 1,
      sym_external_modifier,
    ACTIONS(216), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    STATE(46), 3,
      sym_external_declaration,
      sym_function_definition,
      aux_sym_source_file_repeat1,
  [1638] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(218), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1651] = 4,
    ACTIONS(220), 1,
      aux_sym_string_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(54), 2,
      aux_sym_string_repeat1,
      aux_sym_string_repeat2,
    ACTIONS(222), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1668] = 4,
    ACTIONS(224), 1,
      aux_sym_string_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(50), 2,
      aux_sym_string_repeat1,
      aux_sym_string_repeat2,
    ACTIONS(226), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1685] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(229), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1698] = 4,
    ACTIONS(234), 1,
      aux_sym_symbols_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(52), 2,
      aux_sym_string_repeat1,
      aux_sym_symbols_repeat1,
    ACTIONS(231), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1715] = 4,
    ACTIONS(238), 1,
      aux_sym_symbols_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(55), 2,
      aux_sym_string_repeat1,
      aux_sym_symbols_repeat1,
    ACTIONS(236), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1732] = 4,
    ACTIONS(240), 1,
      aux_sym_string_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(50), 2,
      aux_sym_string_repeat1,
      aux_sym_string_repeat2,
    ACTIONS(242), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1749] = 4,
    ACTIONS(246), 1,
      aux_sym_symbols_token1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    STATE(52), 2,
      aux_sym_string_repeat1,
      aux_sym_symbols_repeat1,
    ACTIONS(244), 3,
      anon_sym_BSLASH_BSLASH,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1766] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(248), 6,
      ts_builtin_sym_end,
      anon_sym_SEMI,
      anon_sym_RBRACE,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1779] = 3,
    ACTIONS(252), 1,
      anon_sym_SEMI,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(250), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1793] = 3,
    ACTIONS(256), 1,
      anon_sym_SEMI,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(254), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1807] = 4,
    ACTIONS(260), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(59), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(258), 3,
      aux_sym_string_token1,
      anon_sym_BSLASH_DQUOTE,
      aux_sym_string_token2,
  [1823] = 2,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(263), 5,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      sym_ident,
  [1835] = 4,
    ACTIONS(265), 1,
      anon_sym_BSLASH_BSLASH,
    STATE(61), 1,
      aux_sym_string_repeat1,
    ACTIONS(3), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(258), 3,
      aux_sym_symbols_token1,
      anon_sym_BSLASH_SQUOTE,
      aux_sym_symbols_token2,
  [1851] = 5,
    ACTIONS(268), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_EQ,
    STATE(63), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(89), 1,
      sym_condition,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1868] = 5,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    ACTIONS(275), 1,
      anon_sym_EQ,
    STATE(63), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(89), 1,
      sym_condition,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1885] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(277), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1896] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(279), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1907] = 5,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    ACTIONS(283), 1,
      anon_sym_EQ,
    STATE(63), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(89), 1,
      sym_condition,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1924] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(285), 4,
      ts_builtin_sym_end,
      sym_ident,
      sym_entry_modifier,
      sym_external_modifier,
  [1935] = 5,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    ACTIONS(289), 1,
      anon_sym_EQ,
    STATE(62), 1,
      aux_sym_sentence_eq_repeat1,
    STATE(89), 1,
      sym_condition,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1952] = 4,
    ACTIONS(291), 1,
      anon_sym_SEMI,
    ACTIONS(293), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_function_name_list_repeat1,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1966] = 4,
    ACTIONS(296), 1,
      anon_sym_SEMI,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    STATE(69), 1,
      aux_sym_function_name_list_repeat1,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1980] = 4,
    ACTIONS(298), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_SEMI,
    STATE(70), 1,
      aux_sym_function_name_list_repeat1,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [1994] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(302), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2003] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(304), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2012] = 3,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    STATE(57), 1,
      sym_body,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2023] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(306), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2032] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(308), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2041] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(310), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2050] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(291), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [2059] = 3,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym_body,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2070] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(312), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2079] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(314), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2088] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(316), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2097] = 3,
    ACTIONS(318), 1,
      anon_sym_SEMI,
    ACTIONS(320), 1,
      anon_sym_RBRACE,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2108] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(322), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2117] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(324), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2126] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(326), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2135] = 3,
    ACTIONS(328), 1,
      sym_ident,
    STATE(97), 1,
      sym_function_name_list,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2146] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(330), 2,
      anon_sym_SEMI,
      anon_sym_RBRACE,
  [2155] = 2,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
    ACTIONS(332), 2,
      anon_sym_COMMA,
      anon_sym_EQ,
  [2164] = 3,
    ACTIONS(191), 1,
      anon_sym_RBRACE,
    ACTIONS(334), 1,
      anon_sym_SEMI,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2175] = 2,
    ACTIONS(336), 1,
      anon_sym_SEMI,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2183] = 2,
    ACTIONS(338), 1,
      sym_ident,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2191] = 2,
    ACTIONS(340), 1,
      anon_sym_DOT,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2199] = 2,
    ACTIONS(342), 1,
      anon_sym_DOT,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2207] = 2,
    ACTIONS(344), 1,
      sym_ident,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2215] = 2,
    ACTIONS(346), 1,
      sym_ident,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2223] = 2,
    ACTIONS(348), 1,
      anon_sym_SEMI,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
  [2231] = 2,
    ACTIONS(350), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 2,
      sym_comment,
      sym_line_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 60,
  [SMALL_STATE(4)] = 120,
  [SMALL_STATE(5)] = 180,
  [SMALL_STATE(6)] = 224,
  [SMALL_STATE(7)] = 268,
  [SMALL_STATE(8)] = 312,
  [SMALL_STATE(9)] = 356,
  [SMALL_STATE(10)] = 400,
  [SMALL_STATE(11)] = 443,
  [SMALL_STATE(12)] = 486,
  [SMALL_STATE(13)] = 527,
  [SMALL_STATE(14)] = 570,
  [SMALL_STATE(15)] = 613,
  [SMALL_STATE(16)] = 656,
  [SMALL_STATE(17)] = 699,
  [SMALL_STATE(18)] = 737,
  [SMALL_STATE(19)] = 777,
  [SMALL_STATE(20)] = 817,
  [SMALL_STATE(21)] = 857,
  [SMALL_STATE(22)] = 897,
  [SMALL_STATE(23)] = 937,
  [SMALL_STATE(24)] = 977,
  [SMALL_STATE(25)] = 1017,
  [SMALL_STATE(26)] = 1054,
  [SMALL_STATE(27)] = 1079,
  [SMALL_STATE(28)] = 1116,
  [SMALL_STATE(29)] = 1141,
  [SMALL_STATE(30)] = 1166,
  [SMALL_STATE(31)] = 1191,
  [SMALL_STATE(32)] = 1228,
  [SMALL_STATE(33)] = 1265,
  [SMALL_STATE(34)] = 1290,
  [SMALL_STATE(35)] = 1327,
  [SMALL_STATE(36)] = 1363,
  [SMALL_STATE(37)] = 1399,
  [SMALL_STATE(38)] = 1422,
  [SMALL_STATE(39)] = 1445,
  [SMALL_STATE(40)] = 1468,
  [SMALL_STATE(41)] = 1491,
  [SMALL_STATE(42)] = 1513,
  [SMALL_STATE(43)] = 1533,
  [SMALL_STATE(44)] = 1553,
  [SMALL_STATE(45)] = 1575,
  [SMALL_STATE(46)] = 1594,
  [SMALL_STATE(47)] = 1616,
  [SMALL_STATE(48)] = 1638,
  [SMALL_STATE(49)] = 1651,
  [SMALL_STATE(50)] = 1668,
  [SMALL_STATE(51)] = 1685,
  [SMALL_STATE(52)] = 1698,
  [SMALL_STATE(53)] = 1715,
  [SMALL_STATE(54)] = 1732,
  [SMALL_STATE(55)] = 1749,
  [SMALL_STATE(56)] = 1766,
  [SMALL_STATE(57)] = 1779,
  [SMALL_STATE(58)] = 1793,
  [SMALL_STATE(59)] = 1807,
  [SMALL_STATE(60)] = 1823,
  [SMALL_STATE(61)] = 1835,
  [SMALL_STATE(62)] = 1851,
  [SMALL_STATE(63)] = 1868,
  [SMALL_STATE(64)] = 1885,
  [SMALL_STATE(65)] = 1896,
  [SMALL_STATE(66)] = 1907,
  [SMALL_STATE(67)] = 1924,
  [SMALL_STATE(68)] = 1935,
  [SMALL_STATE(69)] = 1952,
  [SMALL_STATE(70)] = 1966,
  [SMALL_STATE(71)] = 1980,
  [SMALL_STATE(72)] = 1994,
  [SMALL_STATE(73)] = 2003,
  [SMALL_STATE(74)] = 2012,
  [SMALL_STATE(75)] = 2023,
  [SMALL_STATE(76)] = 2032,
  [SMALL_STATE(77)] = 2041,
  [SMALL_STATE(78)] = 2050,
  [SMALL_STATE(79)] = 2059,
  [SMALL_STATE(80)] = 2070,
  [SMALL_STATE(81)] = 2079,
  [SMALL_STATE(82)] = 2088,
  [SMALL_STATE(83)] = 2097,
  [SMALL_STATE(84)] = 2108,
  [SMALL_STATE(85)] = 2117,
  [SMALL_STATE(86)] = 2126,
  [SMALL_STATE(87)] = 2135,
  [SMALL_STATE(88)] = 2146,
  [SMALL_STATE(89)] = 2155,
  [SMALL_STATE(90)] = 2164,
  [SMALL_STATE(91)] = 2175,
  [SMALL_STATE(92)] = 2183,
  [SMALL_STATE(93)] = 2191,
  [SMALL_STATE(94)] = 2199,
  [SMALL_STATE(95)] = 2207,
  [SMALL_STATE(96)] = 2215,
  [SMALL_STATE(97)] = 2223,
  [SMALL_STATE(98)] = 2231,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(94),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(25),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(94),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(18),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(60),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(5),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(94),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(49),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__expr, 2, 0, 0), SHIFT_REPEAT(53),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 11),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 12),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 19),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_rhs, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 16),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(36),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(17),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(94),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(49),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__pattern, 2, 0, 0), SHIFT_REPEAT(53),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_lhs, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbols, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 3, 0, 15),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3, 0, 20),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3, 0, 20),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_condition, 4, 0, 25),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbols, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbols, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_expr, 2, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_expr, 2, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, 0, 28),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, 0, 28),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, 0, 23),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, 0, 23),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_pattern, 3, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_pattern, 3, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_grouped_pattern, 2, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_grouped_pattern, 2, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [210] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 5, 0, 0),
  [220] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [222] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [226] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(50),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 4, 0, 0),
  [231] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_symbols_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_symbols_repeat1, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [240] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [246] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 3, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 2, 0, 1),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 6),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [260] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(59),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [265] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 2, 0, 13), SHIFT_REPEAT(21),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 2, 0, 13),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 6),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 3, 0, 1),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_external_declaration, 3, 0, 8),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [291] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 0),
  [293] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_name_list_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 2, 0, 7),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_name_list, 1, 0, 2),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 4, 0, 27),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 3),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 3, 0, 17),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 18),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 2, 0, 9),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 2, 0, 10),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_eq, 3, 0, 22),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 3, 0, 21),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence, 1, 0, 4),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block_end, 2, 0, 14),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block_end, 3, 0, 24),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [330] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sentence_block, 4, 0, 26),
  [332] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_sentence_eq_repeat1, 1, 0, 5),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [342] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [350] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_refal5(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
